### ISSUE TITLE
Run SQL Query doesnt work

### ISSUE THREAD

**Issue by DonKolia** [dbm-network/mods#1000]
I have installed the latest version of DBM and the latest version of the mods on another computer.
"I have had a lot of trouble creating a basic command with a simple response message".
Currently nothing works by default with a clean install, also the run_sql_query_MOD mod doesn't work either.
**This has never happened to me with previous versions.**
![image](https://github.com/dbm-network/mods/assets/55564649/49411c60-5d0b-4ca5-8d07-dc492ea020fa)

There's a bug somewhere, because before it wouldn't let me start the Bot. I had to disable something here.
![image](https://github.com/dbm-network/mods/assets/55564649/ae224a94-baf0-492a-a4e2-9e7d5165ffbe)

If I check this box, the bot does not start. The bot on another computer works, on this clean install it doesn't work and doesn't start.
![image](https://github.com/dbm-network/mods/assets/55564649/6b6b2019-32e5-4ace-826d-088c970302ee)

The version is bugged or the extensions are wrong, this has never happened to me before, it's the first time everything is going very wrong. A user who has bought the program will put a negative review because with a clean install, the Bot does not start.

**Comment by DonKolia** [comment]
If u download this modpack, is working: https://dbm-network.org/mods
![image](https://github.com/dbm-network/mods/assets/55564649/f62b459d-a5fe-4de1-8e93-6402d79c5e21)

**Comment by TheMonDon** [comment]
You have to download every single action, individual mods will not work.


Also the other error is not related to the actual mod, it looks like you didn't enable the intent in bot portal or your bot is in over 100 servers

**Comment by DonKolia** [comment]
Thanks, is working now.
Now this is not worling [other "bug"]
![image](https://github.com/dbm-network/mods/assets/55564649/3f1d28a7-464d-49a5-9dda-26ba24535c95)
![image](https://github.com/dbm-network/mods/assets/55564649/44d04892-f5fe-4831-bba0-8a9ced3cf2b1)
No matter what I type in the JSON Path field, it doesn't work and the bot always responds the same.

**Comment by DonKolia** [comment]
Nah, is working. U need put a text in the Message "Check the format of row, if is VARCHAR or DECIMAL"

**Comment by DonKolia** [comment]
Where is the "is not Equals"?, i mean !equals
![image](https://github.com/dbm-network/mods/assets/55564649/a86226fd-3fe5-45dc-9994-eb8fd6ea8cbb)
