### ISSUE TITLE
Reaction List Function Not Found

### ISSUE THREAD

**Issue by KanoCodez** [dbm-network/mods#1001]
**Discord Bot Maker version (master branch only supports 2.1.X)**
- [x] >2.2.X

**Describe the bug**
When using the store reaction info block and attempting to use list all users it comes out with a function not found error.

**To Reproduce**
1. Create a message with a reaction added to it
3. Create a store reaction info block set to list
4. Make it send the list of reacted users
5. It errors with "rea.users.cache.array is not a function"

**Expected behavior**
Expected to give a list of users who reacted

**Screenshots**

![image](https://github.com/dbm-network/mods/assets/83655102/5a782a52-ab3a-4d3a-983a-c981be9972f0)
![image](https://github.com/dbm-network/mods/assets/83655102/ac5e67ac-cce4-448d-ab34-9031ed364089)

**Error messages**
? C:\Users\[Redacted]\Desktop\Bot\actions\store_reaction_info_MOD.js:117
?      result = rea.users.cache.array(); // All users who reacted list
?      ^
?
? TypeError: rea.users.cache.array is not a function
?     at Object.action [as Store Reaction Info] (C:\Users\[Redacted]\Desktop\Bot\actions\store_reaction_info_MOD.js:117:34)
?     at Object.Actions.callNextAction (C:\Users\[Redacted]\Desktop\Bot\bot.js:1511:21)
?     at C:\Users\[Redacted]\Desktop\Bot\actions\find_reaction_MOD.js:78:12
?     at processTicksAndRejections (node:internal/process/task_queues:96:5)
?
? Node.js v17.4.0
?

**Comment by TheMonDon** [comment]
Fixed, redownload mods
