### ISSUE TITLE
send_mail_MOD.js

### ISSUE THREAD

**Issue by DonKolia** [dbm-network/mods#1008]
I am suing the last version. DBM 2.1.7
send_mail_MOD.js dont work

![image](https://github.com/dbm-network/mods/assets/55564649/a3e17495-e9a1-4aba-bec2-4edc24f15f25)
Simple project, and dont work
![image](https://github.com/dbm-network/mods/assets/55564649/557487ee-c688-49f3-930c-c71038469d0f)

**Comment by TheMonDon** [comment]
Issue already reported on GitHub

**Comment by DonKolia** [comment]
If it is impossible to fix, sometimes it is better to remove the extension.
