### ISSUE TITLE
Add | Being able to use variables in the slash responds command

### ISSUE THREAD

**Issue by DonKolia** [dbm-network/mods#1009]
Is easy understand this suggestion:
![image](https://github.com/dbm-network/mods/assets/55564649/743bfa9b-3ef3-46d0-ad6c-4237ac4bce02)
![image](https://github.com/dbm-network/mods/assets/55564649/98a9dc40-1b90-4d07-bfbc-f19be812caae)
![image](https://github.com/dbm-network/mods/assets/55564649/6e66b5d5-fb8e-4b65-9097-8684323bd7e2)

Is not a bug, is a suggestion, make the variables in the slash command responses work, so we can create different messages all the time.

**Comment by Phyrok** [comment]
Use "Send Message" make it ephemeral and place the message there.

The Default response it just there is no other response is set.
![image](https://github.com/dbm-network/mods/assets/69722956/a24a0f55-7b78-4827-a018-6ac19c51094e)
![image](https://github.com/dbm-network/mods/assets/69722956/70ee1e19-9d95-46d6-80b0-f92c478a8b18)
![image](https://github.com/dbm-network/mods/assets/69722956/1d4ddde3-19b7-4198-8dfa-6c31f6a2833f)

**Comment by DonKolia** [comment]
Very thanks! It's working!
