### ISSUE TITLE
YT Info/YT Title

### ISSUE THREAD

**Issue by KanoCodez** [dbm-network/mods#1010]
**Describe the bug**
When getting youtube title from the link it returns undefined 

**To Reproduce**
1. Use Get Youtube info from link
3. Prints out Undefined 

**Expected behavior**
Prints the video title

**Screenshots**
![image](https://github.com/dbm-network/mods/assets/83655102/84630e76-d7e8-485d-8575-24b4edbdb37c)

**Error messages**
`> https://www.youtube.com/watch?v=EFCjlhaKDsQ undefined
? Error with the Command "ytvid" - Action #5 (Send Message):
? DiscordAPIError: Unknown interaction
?     at RequestHandler.execute (C:\Users\%USER%\Desktop\%BOT%\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
?     at runMicrotasks ()
?     at processTicksAndRejections (node:internal/process/task_queues:96:5)
?     at async RequestHandler.push (C:\Users\%USER%\Desktop\%BOT%\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
?     at async CommandInteraction.reply (C:\Users\%USER%\Desktop\%BOT%\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:103:5)
?`

**Comment by OneAndonlyFinbar** [comment]
This isn't a mod issue, [seek help in our discord](https://discord.gg/DMDvzSe).
