### ISSUE TITLE
Run MariaDB Query

### ISSUE THREAD

**Issue by iazex** [dbm-network/mods#1012]
**Is your feature request related to a problem? Please describe.**
The tool currently does not support the direct execution of queries in MariaDB databases, which is a limitation for users who work with MariaDB.

**Describe the ideal solution**
An integrated "Run MariaDB Query" feature would be ideal, enabling direct SQL query execution within MariaDB databases. This feature should offer similar functionality to "Run MySQL Query," tailored for MariaDB.

**Describe alternatives you've considered**
As an alternative, the "Run Script" feature can execute queries indirectly, but it is not as straightforward and lacks the convenience of direct query execution.

**Additional context**
Providing MariaDB support would enhance the tool's utility for MariaDB users, streamlining database management tasks without resorting to less integrated alternatives.

---

**Comment by TheMonDon** [comment]
You can already use mysql. Any mysql client is compatible with mariadb

**Comment by OneAndonlyFinbar** [comment]
The action works just fine with mariadb databases, I've used it myself.
