### ISSUE TITLE
DiscordAPIError

### ISSUE THREAD

**Issue by BozydarBelkot** [dbm-network/mods#1016]
Error:
`DiscordAPIError: Invalid Form Body
0.options[0].description: Must be between 1 and 100 in length.
1.options[0].description: Must be between 1 and 100 in length.
2.description: This field is required
3.description: This field is required
4.description: This field is required
5.options[0].description: Must be between 1 and 100 in length.
5.options[1].description: Must be between 1 and 100 in length.
6.description: This field is required
7.description: This field is required
8.options[0].description: Must be between 1 and 100 in length.
9.options[0].description: Must be between 1 and 100 in length.
9.options[1].description: Must be between 1 and 100 in length.
10.description: This field is required
11.options[0].description: Must be between 1 and 100 in length.
12.description: This field is required
13.description: This field is required
14.description: This field is required
15.description: This field is required
16.options[0].description: Must be between 1 and 100 in length.
17.options[0].description: Must be between 1 and 100 in length.
    at RequestHandler.execute (D:\DBots\Pook\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (D:\DBots\Pook\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async GuildApplicationCommandManager.set (D:\DBots\Pook\node_modules\discord.js\src\managers\ApplicationCommandManager.js:162:18) {
  method: 'put',
  path: '/applications/1177015833898262528/guilds/1001107045568741437/commands',
  code: 50035,
  httpStatus: 400,
  requestData: {
    json: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object]
    ],
    files: []
  }
}`

**Comment by master3395** [comment]
What mod is this error coming from?
Have you tried a clean bot, and see if the issue is coming from 1 action, command, event etc?

What DBM version are you using, when you get this error?

**Comment by Phyrok** [comment]
You need to add a title in your Embed Fields, they can't be empty.
