### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by AustinG921** [dbm-network/mods#1030]
**Discord Bot Maker version (master branch only supports 2.1.X)**
- [ ] 1.6.X
- [ ] 2.1.X
- [ ] 2.2.X
- [ X ] >2.2.X

**Describe the bug**
There is something wrong with Emojis there not loading properly 

![Screenshot_38](https://github.com/dbm-network/mods/assets/130521460/358d98c3-4e61-464d-ba1e-3d1bb84ef783)

**Comment by OneAndOnlyFinbar** [comment]
what action is this?

**Comment by Shadow8814life** [comment]
i saw this with the send message action when you right click and click inset emoji, not sure if its doing it to the mods too though. im thinking its a bug with dbm not mods

**Comment by OneAndOnlyFinbar** [comment]
yeah i think this is probably a bug with the base program

**Comment by AustinG921** [comment]
Yea that’s what I was thinking the fix it windows key + .Sent from my iPhoneOn Mar 31, 2024, at 8:13 PM, OneAndOnlyFinbar ***@***.***> wrote:﻿
yeah i think this is probably a bug with the base program
