### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by St3ph32** [dbm-network/mods#181]
I found this bug:

I use the **Get Bot as Member** with a variable of any name.
Then the **Check Member Permission** of the **Get Bot as Member** variable

And the bot, even if it does not have the permissions, goes beyond the **Check Member Permission**.
Resolve as soon as possible I need these commands.

Excuse me for english...

**Comment by Almeeida** [comment]
Those actions work perfectly since I've used them before.

**Comment by St3ph32** [comment]
I will try the command again later, if it doesn't work I'll send a screenshot.

**Comment by St3ph32** [comment]
Still not working, here are some screenshots:


![screenshot_1](https://user-images.githubusercontent.com/44477728/58432490-ed94d980-80b2-11e9-8f07-7f1d4cf3529a.png)

![screenshot_2](https://user-images.githubusercontent.com/44477728/58432497-f38aba80-80b2-11e9-89d0-5379f580e6e1.png)

**Comment by St3ph32** [comment]
Anyone can help me?

**Comment by DetroitWhiskey136** [comment]
For better support I suggest using the mods support server on discord https://discord.gg/3QxkZPK or the Support website found https://dbm-support.site/

**Comment by TheMonDon** [comment]
@St3ph32 Have you resolved this issue?

**Comment by dupetion** [comment]
I will try doing this today and will notify you if that works or not but as far as my guess goes , after making the bot a member , you need to store it as a data like data member as well

**Comment by Almeeida** [comment]
Closing this issue since it hasn't had any activity recently.

**Comment by TheCubiq** [comment]
> For better support I suggest using the mods support server on discord https://discord.gg/3QxkZPK or the Support website found https://dbm-support.site/

![image](https://github.com/dbm-network/mods/assets/70297468/9f887bf6-cf4f-4112-a141-5642cde2b446)
