### ISSUE TITLE
Music is completly broken

### ISSUE THREAD

**Issue by DasDavid** [dbm-network/mods#199]
**Playing music is completly broken.** You either get an error that "lenght" is undefined, or it says this when you try to play a song:
![or This](https://user-images.githubusercontent.com/38788415/59967502-031ee700-952b-11e9-9247-4c336df66d10.PNG)
(Here's the "lenght" error)
![This](https://user-images.githubusercontent.com/38788415/59967506-12059980-952b-11e9-810c-3f91462b2faa.PNG)
I tried to reinstall every node module (through dbm and independently) aswell through dbm. Also I started the bot always independently (going into the Project folder and opening cmd there or directing there with "cd" and then running 'node bot.js'). 
It wont work at all. I even tried to reinstall dbm and dbm mods, also installing dbm mods beta and updating all the mods manually.
Seems to be common to:
![Not working](https://user-images.githubusercontent.com/38788415/59967673-aa048280-952d-11e9-8d6e-5d7a74e24da1.PNG)

**Comment by DasDavid** [comment]
I you need to see my actions list:
![Actions list](https://user-images.githubusercontent.com/38788415/59967572-43cb3000-952c-11e9-8948-9e0c990394b0.PNG)
I **have** given a valid youtube v3 api too!
Also certain songs **work** (**Example**: "One step closer") and some **don't** (**Example**: "One more light")

**Comment by Masiakig** [comment]
Bug Common problem

**Comment by Masiakig** [comment]
me too

**Comment by Almeeida** [comment]
Is this still happening after the new update?
