### ISSUE TITLE
Loop through list combined with member voice channel is bugged

### ISSUE THREAD

**Issue by manugd14** [dbm-network/mods#220]
So when we use Store Member Info - Member voice channel in a command, it does the job. Will return the current user´s voice channel, or undefined if the user is not on a voice channel at this time.

The problem, wen I loop a list of members through an event that should store the member voice channel, once the list hits a member that is NOT on any voice channel, it will return the voice channel from the PREVIOUS member on the list, instead of undefined. Making it unusable. 

As seen in this screenshot, the first time I execute the command, no users from the list are in a voicechannel until the last one, so everybody results in undefined. 
The second time I execute the command, I added one user more to the list, which is in a voice channel, so him, and all the following users, report to be in the same voice channel. 

https://cdn.discordapp.com/attachments/374961417016573962/614822889480257544/unknown.png

in this screen, the same thing with game info
[image](https://user-images.githubusercontent.com/54359435/63638778-cb4c3100-c68c-11e9-9b3c-5c7bb1e9a023.png)

**Comment by Almeeida** [comment]
I will be closing this issue since it's old and hasn't had any recent activity. If the issue persists, feel free to reopen/create a new ticket. You can also use the support channel on Discord if you feel like it. https://discord.gg/3QxkZPK
