### ISSUE TITLE
Can't Set Member Channel Perms in Modded version

### ISSUE THREAD

**Issue by Jake11The11** [dbm-network/mods#253]
I can't set a member's channel perms in the modded version, but it works in the beta version perfectly fine.

**Comment by ForceBlood** [comment]
Can you give us some more information like if there are errors in cmd and etc?

**Comment by Jake11The11** [comment]
When I try and run the Set Member Channel perms action, in cmd it says “Set Member Channel Perms doesn’t exist”

**Comment by ForceBlood** [comment]
copy the Set Member Channel Perms action from your dbm's actions directory and paste it into your bot's directory

**Comment by Jake11The11** [comment]
I tried copying the SMCP action (Set Member Channel Perms) from the beta version and pasted it over the modded SMCP action, but the same message in cmd still appeared.
https://gyazo.com/9807566bc3fb7d1b633d2e6a534f7266

**Comment by Almeeida** [comment]
You need to copy the "Set **Role** Channel Perms" action into your project's actions directory. (That's what you screenshot says.)

**Comment by Almeeida** [comment]
I will be closing this issue since it's old and hasn't had any recent activity. If the issue persists, feel free to reopen/create a new ticket.
