### ISSUE TITLE
Create Text Channel does not work

### ISSUE THREAD

**Issue by K1LL3RZERO** [dbm-network/mods#254]
Every time my bot tries to create a channel it just comes with the response of 

`Error with Event "Create Text Channel",Action #1:DiscordAPIError:Invalid Body type: Value "text" is not int.`

Could someone help me?

**Comment by KendyCZ01** [comment]
Try in console `npm i discord.js`

**Comment by K1LL3RZERO** [comment]
> Try in console `npm i discord.js`

Well this fixed my original problem with the bot. But now there is another problem. Whenever I would start my bot now it would instantly stop. whether it was in DBM itself or if I was using the command prompt. I really don't understand why its doing this tbh. Think anyone could help me on this as well?

**Comment by Almeeida** [comment]
I will be closing this issue since it's old and hasn't had any recent activity. If the issue persists, feel free to reopen/create a new ticket. You can also use the support channel on Discord if you feel like it. https://discord.gg/3QxkZPK
