### ISSUE TITLE
Search bar not working after update

### ISSUE THREAD

**Issue by DogV2** [dbm-network/mods#268]
The search bar (https://i.imgur.com/SBKrlmt.png) does not function after updating to the newest dbm beta version, cache has been cleared 3 times, used the "everything" program & no DBM/DBM2 etc folders were there, re-installed actions, verified files & still no results, multiple people also having this issue

**Comment by dcorvus** [comment]
Why are you submitting a bug report, for the software, on the network mods bug tracker.
