### ISSUE TITLE
Store Message Info > Message Embed Object not storing Author Icon URL

### ISSUE THREAD

**Issue by AlexandreCastilho** [dbm-network/mods#288]
Store Message Info > Message Embed Object is not storing the Author Icon URL.
 I've tried to use Store Embed Info - Author Icon URL, and it returns "TypeError: Cannot read property '0' of undefined".

**Comment by AlexandreCastilho** [comment]
Correction: Store Embed Info - Author Icon URL was giving this error due to wrong variable specification.
But still, if the embed object is sent in a message, it goes without the author icon.

**Comment by Almeeida** [comment]
Update **beta** mods.
