### ISSUE TITLE
await_response_call_action_MOD.js seems to be ignoring the filter

### ISSUE THREAD

**Issue by JasperEdits** [dbm-network/mods#291]
The "JavaScript Filter" looks like is being ignored in the last version of the mod.

**Comment by ForceBlood** [comment]
Can you please screenshot your await response call action or provide the javascript filter

**Comment by JasperEdits** [comment]
Sure:
![image](https://user-images.githubusercontent.com/28309837/75794924-ce2d8a00-5d71-11ea-831d-688f3b788997.png)
This is how my action looks like, I've tried:

- content.length > 0 && author.id === tempVars('member.id') 
(tempVars('member.id') being the command author's id.)
-  author.id === user.id
- I even tried to do: author.id !== user.id (and it let me awnser with any account.)

**Comment by ForceBlood** [comment]
i used `content.length > 0 && author.id === user.id` and it works

**Comment by JasperEdits** [comment]
I don't know how it's not working on my end then.

**Comment by Almeeida** [comment]
Type `npm ls discord.js` on the console

**Comment by JasperEdits** [comment]
Okay, I think I understand:
I had the 11.6.1 version of discord.js, I'm gonna try installing the 11.5.1 one.

**Comment by JasperEdits** [comment]
![image](https://user-images.githubusercontent.com/28309837/75802820-a04e4280-5d7d-11ea-969d-cb38ccbf5bc3.png)
Didn't work.

**Comment by JasperEdits** [comment]
The mod/rd is are not the problem.
It's either the package.json or something else, I tried another rd that I have in another bot (that works) and it doesn't on this one.

I also tried copying the package.json contents and It doesn't work either, I'm out of ideas.

**Comment by JasperEdits** [comment]
I did `npm i discord.js@11.5.1` and now I get this
![image](https://user-images.githubusercontent.com/28309837/75817435-5d996400-5d97-11ea-9745-1f5d397926a9.png)

The issue hasn't been fixed.

**Comment by JasperEdits** [comment]
Ok! I found a fix, it looks like this happens with the newer version of DBM and glitch, to fix:
First: Your bot > `package.js`:
Add:
```
    "jimp": "^0.8.5",
    "discord.js": "11.5.1",
```

Then: Logs > Console:
`npm i discord.js@11.5.1` > (Wait)
`npm i jimp@^0.8.5` (Wait)
(jimp breaks after installing discord.js, that's why you need to install it after you got discord.js working, I don't know why tf it breaks but it does 🤷‍♂)

When everything is installed: Restart bot (by changing a file (NOT `package.json`, DON'T BREAK IT)
