### ISSUE TITLE
Store Json From WebAPI not looking in the right place

### ISSUE THREAD

**Issue by Whitewatt** [dbm-network/mods#296]
**Describe the bug**
The Mod named in the title is trying to look for request module in the equivalent of china or something, in /usr/local/lib/node_modules/pm2/lib/node_modules/request instead of the bot's root folder node_modules folder. There ain't no node_modules inside the pm2 lib folder, but there is one in the pm2 folder. 

**To Reproduce**
1On Scaleway with Ubuntu Bionic
2Installed npm
3Installed pm2
4Threw the bot on home folder
5Ran NPM I
6Ran the modules that didn't auto install because of reasons
7Tried a command with Store Json From WebAPI
8It tries to install request
9fsevents can't, don't care because I manually installed request anyway
10 https://pastebin.com/p5aXZQDc

**Expected behavior**
Should look for the module in the bot's root folder's node_modules folder!

**Comment by Almeeida** [comment]
Most likely an issue with the automatic module installer and not Store JSON From WebAPI directly.

**Comment by Almeeida** [comment]
https://github.com/dbm-network/mods/issues/348 and https://github.com/dbm-network/mods/issues/337
(Fixed in v12)
