### ISSUE TITLE
Await response mod doesn't use the JS filter

### ISSUE THREAD

**Issue by TheSalvy** [dbm-network/mods#298]
**Describe the bug**
When you use the await response mod, it will be triggered with any message, it ignores the JS filter.

**To Reproduce**
1. Add the action
2. Use this filter: `['yes', 'no'].includes(content.toLowerCase()) && author.id === tempVars('userid')`
3. Start the command and have someone else trigger the mod

**Expected behavior**
It should only respond when the answer is yes or no and when the command author sends the message

**Comment by Mndlsscrg** [comment]
around the tempVars('userid') did you try putting ' ' like this > 'tempVars('userid')'

**Comment by TheSalvy** [comment]
> around the tempVars('userid') did you try putting ' ' like this > 'tempVars('userid')'
> 
> Edit : Confirmed this is a user error. Try using `['yes', 'no'].includes(content.toLowerCase()) && author.id === '${tempVars('userid')}'` It should work

I did as you said but it ignored both user and content filter
https://i.imgur.com/JYaINaf.png
https://i.imgur.com/PjKRRvz.png

**Comment by Almeeida** [comment]
Is the action called `Await Response v1.0.0` on the editor?
