### ISSUE TITLE
Store Invite Info not returning some infos

### ISSUE THREAD

**Issue by Dinip** [dbm-network/mods#299]
**Describe the bug**
Store Invite Info mod is not returning some infos like creation date, expiration date, max usages, times used. 

**To Reproduce**
1 - Create a store command params action to receive the invite code;
2 - Create a store invite info action and set source invite to variable created previously and set source info to times used;
3 - Create a send message and send the variable created with the info from setup 2.
4 - Returns undefined

**Expected behavior**
Return times used, creation date, max usages...

**Screenshots**
![image](https://user-images.githubusercontent.com/8941012/77186467-d3f1d200-6aca-11ea-9ef3-69385aa13d31.png)

**Comment by LeonZ2019** [comment]
@Dinip ,what is your discord name in Network?

**Comment by Dinip** [comment]
Just joined discord network now, @Dinip#7890

**Comment by Almeeida** [comment]
That's to be expected. ![image](https://i.imgur.com/eSQgixV.png)

**Comment by Dinip** [comment]
@LeonZ2019 send me a modified file via discord and seems to work now
![jmE289Xu68](https://user-images.githubusercontent.com/8941012/77234797-1b4e9000-6ba9-11ea-8589-611343deb07a.png)

**Comment by JMK19** [comment]
> @LeonZ2019 send me a modified file via discord and seems to work now
> ![jmE289Xu68](https://user-images.githubusercontent.com/8941012/77234797-1b4e9000-6ba9-11ea-8589-611343deb07a.png)

Do you mind letting me know what this was and how it fixed it?

**Comment by UnoSite** [comment]
Store Invite Info - Times Used

Times used returns NULL

![Anmærkning 2020-07-29 225204](https://user-images.githubusercontent.com/68971788/88852422-8c085780-d1ee-11ea-8c28-38a4e867803c.png)
![Anmærkning 2020-07-29 225412](https://user-images.githubusercontent.com/68971788/88852427-8ca0ee00-d1ee-11ea-8135-e1196f7e5275.png)

`// The version of the mod (Defaults to 1.0.0)
 version: "1.9.5", //Added in 1.9.0`

**Comment by dzfnx** [comment]
Please help me, I'm trying to create too but it's not working

**Comment by dzfnx** [comment]
@LeonZ2019 Please help me! Discord: Dëzin#7714
