### ISSUE TITLE
Find Message failing to fetch messages sent before start

### ISSUE THREAD

**Issue by JasperEdits** [dbm-network/mods#303]
**Describe the bug**
The Find Message action is not being able to find a message by its id sent before the bot started, returning undefined.

**To Reproduce**
1. Send a message
2. Store its id
3. [In an event] add Find Message action > input id
4. Returns undefined

**Expected behavior**
Should be storing the message correctly.

**Comment by Almeeida** [comment]
What event type are you using? Can not replicate using a command.

**Comment by JasperEdits** [comment]
Try to replicate it within an event. This are my events that are not completely working:
![image](https://user-images.githubusercontent.com/28309837/77559438-7be91000-6ebc-11ea-9990-51c13a012e40.png)
![image](https://user-images.githubusercontent.com/28309837/77559505-902d0d00-6ebc-11ea-9322-bf47817cccac.png)

**Comment by Almeeida** [comment]
Just tried it, cannot replicate.

**Comment by JasperEdits** [comment]
Weird, I'll try some more stuff and close the issue later.

**Comment by Almeeida** [comment]
Here's the setup I tried:
![0ZphTTp](https://user-images.githubusercontent.com/42935195/77560622-9ec3f600-6eb5-11ea-9070-ac802075b9a0.png)
![oAzetPg](https://user-images.githubusercontent.com/42935195/77560663-aa172180-6eb5-11ea-84d6-03edccce9e98.png)

**Comment by JasperEdits** [comment]
Try to find the message using channel stored in a server variable, that's the thing that is returning undefined now that I'm checking.
Make sure that the bot didn't interact with the channel when it's fetching the message after you start the bot.

Maybe the event is not loading the server variables correctly?

**Comment by Almeeida** [comment]
I suppose it wouldn't load the server variables since there's no server in that loop. Try using `Find Server` > `Change Server` at the beginning of the loop event.

**Comment by JasperEdits** [comment]
Ahh okay, I could save the server id in the .json file and retrieve it.
Thanks!
