### ISSUE TITLE
Loop through list calling events twice

### ISSUE THREAD

**Issue by JasperEdits** [dbm-network/mods#304]
_I hope this one isn't somehow my fault._ 

**Version and more information**
BETA Version 1.5.10
Lastest beta mods (downloaded a week ago)

**Describe the bug**
Loop through list is calling events twice.

**To Reproduce**
1. Create "on interval" event
2. Add loop through list event
3. Start the bot and make the watch it run twice

**Expected behavior**
Should be calling them once.

**Videos**
https://youtu.be/0vJfIhO-fQ4

**Comment by Almeeida** [comment]
Is your bot, by chance, in 2 guilds?

**Comment by JasperEdits** [comment]
> Is your bot, by chance, in 2 guilds?

It is, yes, but why does that affect the action?

**Comment by Almeeida** [comment]
Because the event runs once per guild.

**Comment by JasperEdits** [comment]
> Because the event runs once per guild.

That's kinda weird, there should be a way to work around that or disable it, right?

**Comment by Almeeida** [comment]
> > Because the event runs once per guild.
> 
> That's kinda weird, there should be a way to work around that or disable it, right?

It's how DBM bots work by default, nothing we can do about disabling it. But you can work around it with a Run Script on a Bot Initialization event, using the "Run Action Sequence Once" action on it (Since this event also runs once per guild) and making use of the `setInterval()` method.

**Comment by JasperEdits** [comment]
> > > Because the event runs once per guild.
> > 
> > 
> > That's kinda weird, there should be a way to work around that or disable it, right?
> 
> It's how DBM bots work by default, nothing we can do about disabling it. But you can work around it with a Run Script on a Bot Initialization event, using the "Run Action Sequence Once" action on it (Since this event also runs once per guild) and making use of the `setInterval()` method.

Thanks, that's really helpful, let's see if next time I create an issue it's not actually my fault xd.
