### ISSUE TITLE
[VIDEO] Store Reaction Info returning null sometimes

### ISSUE THREAD

**Issue by JasperEdits** [dbm-network/mods#306]
*I hope I'm not bothering anyone by making these issues. 
To be clear, I tried to ask for some help on the Discord servers but to no avail, and after doing some more tests I decided to make an issue about it 😓*

**Describe the bug**
Store Reaction Info is not being able to return members who reacted to a reaction that was added before the bot started.

**To Reproduce**
[YouTube video showing off my issue](https://youtu.be/jwMaZtpLxfg)

**Expected behavior**
The info should have been stored like it was in the first part of the video.

**Screenshots**
These are some parts of the events that didn't get in the video:
![image](https://user-images.githubusercontent.com/28309837/77824548-cf00d400-7103-11ea-8207-8e51d524b4fb.png)
![image](https://user-images.githubusercontent.com/28309837/77824615-4171b400-7104-11ea-8f96-1cb164a971ce.png)

**Comment by JasperEdits** [comment]
If there is an issue with the mods It might be Wrex's dependencies fault:
![image](https://user-images.githubusercontent.com/28309837/77824692-d1176280-7104-11ea-933c-87e104dafb62.png)
Cause to me, the actual Store Reaction Info mod looks just fine...:
![image](https://user-images.githubusercontent.com/28309837/77824703-ebe9d700-7104-11ea-854e-8ad00b59cca5.png)

Not sure tho!

**Comment by LeonZ2019** [comment]
Your reaction probably didn't cache because the message is sent before the bot online. Find Reaction action could be improve by fetch the reaction
- discord.js v11
  - fetchUsers()
- discord.js v12
  - fetch()

**Comment by RigidStudios** [comment]
#391 #390 Fixed, this can be closed @Almeeida

**Comment by JasperEdits** [comment]
Thanks, @RigidStudios, my man.
