### ISSUE TITLE
Get command description won't add the variables to the list of variables when you right click

### ISSUE THREAD

**Issue by TheSalvy** [dbm-network/mods#307]
**Describe the bug**
When you use the mod and you store the information as a temp var or any other type, the variable won't show in the list of variables when you right click and you need to manually enter the name.

**To Reproduce**
1. Store description
2. Right-click on a text field
3. Try to find the variable name you saved using store description mod

**Expected behavior**
It is supposed to be shown in list of variables.

**Screenshots**
https://i.imgur.com/JtnZFd2.png
https://i.imgur.com/yzlvg6D.png

**Comment by DetroitWhiskey136** [comment]
This is a known, it is unknown whether or not the developer of the mod will be fixing it, i will bring it to his attention again
