### ISSUE TITLE
set time restriction feature

### ISSUE THREAD

**Issue by master3395** [dbm-network/mods#308]
Not sure if this should go as bug or feature request.
But
set time restriction should allow us to set time restrictions for each user.
Not just for the server or all servers.

Sometimes you have commanded, that should have a cooldown, for each user.

**Comment by HeavyWolfPL** [comment]
That option is called "Adjust Time Restrictions" when you right-click the command.

**Comment by master3395** [comment]
> That option is called "Adjust Time Restrictions" when you right-click the command.

That would stop the command 100%, I want to have a custom reply saying something similar to what i have below.

"This command has been used in the last 30 Seconds..
Please wait around ${tempVars("cooldown-timer")} seconds in order to use it again."

**Comment by RigidStudios** [comment]
There's an event for that! **"On Time Restricted Command"**. You don't even need to use a mod for it!

**Comment by master3395** [comment]
It replies for all users in the server, not just for 1 user, each command.
And for some reason, if i use the "on Time Restricted command", it would reply on every message, if i have "any message" enabled on a command.

> There's an event for that! **"On Time Restricted Command"**. You don't even need to use a mod for it!

**Comment by LeonZ2019** [comment]
You can set the Restrict By to Global
![F38568FB-3AF1-4C5E-B1F6-098F5170713B](https://user-images.githubusercontent.com/10143361/82766760-1f6e8680-9e54-11ea-9830-b8e6e1c72d7c.png)
