### ISSUE TITLE
Send embed message issue

### ISSUE THREAD

**Issue by sungardaJ** [dbm-network/mods#311]
**Screenshot 1** : https://prnt.sc/s0xfb9
**Screenshot 2** : https://prnt.sc/s0xiar
**Screenshot 3** : https://prnt.sc/s0xitz

If you look at screenshot 1, I've stored the channel into a server variable (reportchannel) , in which I would like to use for another command.
Now for the other command I'd like to send an **embed** message to reportchannel, which of course, I have defined earlier. Now the problem is, there's literally no "reportchannel" in the drop down. I tried writing the variable manually and it still won't work. (Check screenshot 2)

Note that the server variable **exists and can be used** in all other actions except for the "Send embed message" action. (Check screenshot 3)

**Comment by RediPanda** [comment]
As far as your screenshots shows, you're not using our modified version of **Send Embed Message** which should fix those issues as well as providing you more options such as storing the message object for later manipulation (add reactions, deleting the message etc.).

**You can find it here:**
https://github.com/dbm-network/mods/blob/beta/actions/send_embed_message.js

This issue will be closed as it's not related to Network Mods. Have a good day!
