### ISSUE TITLE
Create Channel won't work

### ISSUE THREAD

**Issue by MuffinMarvinTV** [dbm-network/mods#314]
? Error with Event "Create Text Channel", Action #1:
? DiscordAPIError: Invalid Form Body
? type: Value "{'type': 'text', 'topic': 'hallo123', 'position': None}" is not int.
?

(Windows 10 Pro)

**Comment by RigidStudios** [comment]
Yes it does work, you've got the wrong Discord.js Version, please perform `npm i discord.js@11.6.4`.

**Comment by RediPanda** [comment]
As @RigidStudios stated,your solution is to upgrade your Discord.JS version to one of the higher versions. This issue will be closed.

**Comment by MuffinMarvinTV** [comment]
And how can I upgrade it on my PC?
