### ISSUE TITLE
Temp Variable showing Server Variable

### ISSUE THREAD

**Issue by LukeMackers** [dbm-network/mods#315]
**Describe the bug**
When I try and put a temp var into the temp var slot it says the only option is a server variable.
And when I switch it around, I put in the server variable and it comes up with temp variable options.

**To Reproduce**
1. Go to send embed message.
2. Click on the "Source Embed Object:" and change it to temp. Then put the "Send To:" as server variable. 
3. Click on the drop down and see your options.

**Expected behavior**
It is obviously supposed to give me my temp and server variables.

**Screenshots**
![image](https://user-images.githubusercontent.com/63143742/79955315-bdc4a080-84d2-11ea-82cc-f92f5c9264a0.png)

![image](https://user-images.githubusercontent.com/63143742/79955453-ee0c3f00-84d2-11ea-8fc1-d4be8f5cd61b.png)

**Comment by RigidStudios** [comment]
Do the temp/server variables still work with the correct values despite the false classification?

**Comment by RigidStudios** [comment]
I can confirm this, not much we can do to my knowledge though, this is how DBM shows variable lists.

**Comment by DetroitWhiskey136** [comment]
after giving this a try i can't say it had the same results, is this still happening?

**Comment by ForceBlood** [comment]
Cant repro.

**Comment by Almeeida** [comment]
Assuming it has been fixed by the new update.
