### ISSUE TITLE
Await response and await reaction mod

### ISSUE THREAD

**Issue by TheSalvy** [dbm-network/mods#325]
Hello there

So await response mod doesn't work on glitch and it ignores the JS filter but await reaction works fine.
As you can see here the await response mod ignored the JS filter: https://i.imgur.com/MnddIyj.png
`['yes', 'no'].includes(content.toLowerCase()) && author.id === tempVars('userid')`
And here it worked just fine for await response mod: https://i.imgur.com/npXuLnK.png
`reaction.emoji.name === '✅' || reaction.emoji.name === '❎' && user.id === '${tempVars("userid")}'`

**Comment by LeonZ2019** [comment]
if you notice the js filter, the one you have works is `'${tempVars("userid")}'` and the other one doesn't works is about `tempVars('userid')`

**Comment by RigidStudios** [comment]
Not a bug, fix: 
```(reaction.emoji.name === '✅' || reaction.emoji.name === '❎') && user.id === '${tempVars("userid")}'```
It's like math priority. @Almeeida This can be closed.
