### ISSUE TITLE
Store Bot Client Info Total Users not caching all users?

### ISSUE THREAD

**Issue by Fisheiyy** [dbm-network/mods#327]
So I am having trouble with store bot client info > total users as its not caching all users from all servers when I run it on a command it works right but it should do it on bot initialization and I made a command that calls it 5 times to try and make it cache all users but it wont work can anyone help me?
Does it matter that my bots in the DBL Server which has 96k users but only counts 26k which idk are coming from other than DBL if not counting them then it should be about 2/3k users.

**Comment by Almeeida** [comment]
That behavior is intended. However, you can fetch all users upon the bot starting using: 
```js
client.guilds.forEach((g) => g.fetchMembers().catch(() = null))
```
