### ISSUE TITLE
Store Server Info

### ISSUE THREAD

**Issue by loganou7** [dbm-network/mods#335]
TypeError: Cannot read property 'size' of undefined

I am using it to store total human members and total online members on the current server. This error is returning. I have the oldest bkp of this Action that does not present this error.

**Comment by JordanWKWhite** [comment]
+1 having same issue.

**Comment by Almeeida** [comment]
Type `npm ls discord.js` on your bot directory and send the result.

**Comment by JordanWKWhite** [comment]
discord-bot-maker-bot@1.5.10 C:\Users\xxxx\Desktop\ArmaLifeBot
`-- discord.js@11.5.1

Apologies for the delayed response.

**Comment by JordanWKWhite** [comment]
Have upgraded to discord.js@11.6.4 with the same issue. I thought I'll give that a try as it's a common theme in the Discord server.

**Comment by JordanWKWhite** [comment]
Can confirm it is working if the older version is restored, thanks to OP for the pointer. For those with this issue, a temp fix would be to restore the old version, which can be found here. https://github.com/dbm-network/mods/blob/557ff87fbe079cb6f75f22a3ba0c9744ab33ee66/actions/store_server_info.js 

To apply it, all you'll need do is open the original store_server_info.js (YourBotName\actions\store_server_info.js, copy the older version in the link provided above, paste it in, overwriting the old content and then save. Be sure to keep a backup of the original. 

I'll look over the difference and see if I can find a fix. #NoobToTheRescue

**Comment by LeonZ2019** [comment]
No a problem any more if you using beta mods, https://github.com/dbm-network/mods/commit/4ce6189bce5f7444d5f94c47ff8366c8758e2e20

**Comment by JordanWKWhite** [comment]
Can confirm it works as long as DBM mods is installed in both DBM directory **and** your bots directory, as said in the install instructions, I have only now been bothered to read. Rip.
