### ISSUE TITLE
aaa_wrexmods_dependencies_MOD.js

### ISSUE THREAD

**Issue by master3395** [dbm-network/mods#337]
I updated the mod from 2.0.1 up to 2.0.5 and any new version after the working 2.0.1
Would try and keep re-installing several node modules.

I have no idea why, but it keeps trying to install the core DBM modules, even if they are installed.

**Comment by RigidStudios** [comment]
Provide some information on your environment, operating system, process managers, etc.

**Comment by master3395** [comment]
Centos 7 64bit.
I run my 2 bots using pm2.

I use Discordjs@11.6.4

![image](https://user-images.githubusercontent.com/4199669/84678769-b351e080-af30-11ea-8b2b-b99dcfa52489.png)

**Comment by manugd14** [comment]
I had that happen once not too long ago with a similar environement (jut on Ubuntu 11.0.4). Only solution was to start a new project and import commands and events.

**Comment by RigidStudios** [comment]
@master3395 Use the [aaa_wrexmods_dependencies_MOD.js](https://github.com/dbm-network/mods/blob/v12/actions/aaa_dbmmods_dependencies_MOD.js) from V12. Or if you don't want to need to make changes, use the file from [my PR](https://github.com/RigidStudios/mods/blob/patch-31/actions/aaa_dbmmods_dependencies_MOD.js)

**Comment by manugd14** [comment]
Does this mean I need to update to alpha and V12?.

**Comment by master3395** [comment]
> @master3395 Use the [aaa_wrexmods_dependencies_MOD.js](https://github.com/dbm-network/mods/blob/v12/actions/aaa_dbmmods_dependencies_MOD.js) from V12. Or if you don't want to need to make changes, use the file from [my PR](https://github.com/RigidStudios/mods/blob/patch-31/actions/aaa_dbmmods_dependencies_MOD.js)

Using you're version or 2.0.1 they both works, the current version today before the pull request from you does not work, as far as i can see.

**Comment by master3395** [comment]
> So is it working now or not?

This version works yes [RigidStudios PR](https://github.com/RigidStudios/mods/blob/patch-31/actions/aaa_dbmmods_dependencies_MOD.js)
