### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by idunnoooooo** [dbm-network/mods#338]
How i can make system like that
If someone got vip role he gets 200 coins every 1 hour (i already got economy system btw)

**Comment by Mindlesscargo** [comment]
This is not the place for this. You can ask in support on the DBM Main or DBM Network server, or request raw data in the network. This is strictly for reporting errors with the code.

**Comment by Almeeida** [comment]
Use the [Discord server](https://discord.gg/3QxkZPK) instead
