### ISSUE TITLE
Store Server Info: Categories 

### ISSUE THREAD

**Issue by JordanWKWhite** [dbm-network/mods#341]
Hello,

As it stands 'Store Server Info: Channel Amount' also stores categories. While we might expect this behaviour, in my use case I needed it to be specifically text and voice channels. If this mod is to be revised, especially with V12, it would be a welcome addition if we can count categories separately.

For time being, I have Store Server Info x2, 1 = store text channels, 2 = store voice channels. Then have a math operation to add them up to form total channels. Just in case anyone needs this workaround. To get totally categories, you can just run the Store Server Info Channel Amount source info, then subtract the result from store text and voice source from the result. You'll then have category count.

Thanks,
Jordan.

**Comment by RigidStudios** [comment]
I wonder why this issue is still open, this was fixed by my PR.
