### ISSUE TITLE
Canvas installation issues

### ISSUE THREAD

**Issue by aman78600** [dbm-network/mods#349]
**Describe the bug**
canvas.node is not a valid Win32 application.
Alot of tries still same error
![Screenshot (414)](https://user-images.githubusercontent.com/55920587/83521913-f5226600-a4f0-11ea-9099-1411573e0372.png)

**Screenshots**

**Comment by RigidStudios** [comment]
Can confirm this happens a lot. However I think this is due to your personal canvas installation, and not the canvas mods we provide.

**Comment by davipatricio** [comment]
This usually means you have mismatched node-canvas and Node.js architectures (32 vs. 64 bit).
