### ISSUE TITLE
Run SQL Query

### ISSUE THREAD

**Issue by Thaliruth** [dbm-network/mods#352]
This mod still doesn't store the MySQL connection as server or global variable on. Temp Variable works fine. But that's all there is to it.

**Comment by Thaliruth** [comment]
I have detected that the MySQL connection is stored. But no data is stored in the file ServerVars.json. After a bot restart it loses the stored MySQL data. I have to execute a mysql command again which saves it ServerVars technically. This storage only lasts until the bot is restarted.

**Comment by RigidStudios** [comment]
@Thaliruth You actually have to use **Save Variable** to do this. This isn't a bug, just how the app is intended to work. @Almeeida ;)

**Comment by Thaliruth** [comment]
I had already used Save Variable, and the result in my servervars.json was just that it said FALSE and nothing more. So it would be nice if you check your mods a bit more carefully before publishing anything.

**Comment by Thaliruth** [comment]
But you just close down without testing yourself, it's funny but OK ;) Unfortunately you don't really know the network any other way ^^
