### ISSUE TITLE
Member Update event with Username change

### ISSUE THREAD

**Issue by manugd14** [dbm-network/mods#366]
**Describe the bug**
- Store member info action with store username basically works fine to obtain the username of a member at a certain point of time. 
- Member update trigger works triggering an event when a member updates some information about itself (like displayname, username or others). In particular, the event fails to trigger with username or tag changes. It triggers fine with displayname changes though. 

**To Reproduce**
1. Create a new event with member update trigger and store the member before the change as "memberPre" and the member after the change as "memberPost"
2. Create two store member info actions that will store member username (one from memberPre (as usernamePre) and the other one from memberPost (as usernamePost)). 
3. Enter a send message action that will send to a default (or other) channel a message containing the temp variables memberPre and memberPost. 
4. Change your username in discord. You will get no message on the designated channel. If you go back and change the store member info actions to store member displayname, and then change your displayname, you will get a message on the designated channel with your previous and current display names. 

**Expected behavior**
I expect the event to be triggered and to receive a message with the previous and current username after a username change. Just like it happens with display names.

**Comment by RigidStudios** [comment]
You're saying that Member Username updates don't trigger the Member Update event?

**Comment by manugd14** [comment]
Correct, they do not. Other changes (like nickname, presence, and others do it fine).

Username changes do not trigger the event.
Discriminator changes I don't know (i have no nitrox to test)

**Comment by RigidStudios** [comment]
Found the cause, it likely works on the wrong trigger, it should be using [this](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-userUpdate), I'll pull an Event later today, thanks for the report.

**Comment by manugd14** [comment]
No problem, thank you.

**Comment by RigidStudios** [comment]
I've pulled it, it's on [the events repo](https://github.com/dbm-network/events/pull/11) if you want to use it before it's accepted.
