### ISSUE TITLE
Actions v12: Await reaction

### ISSUE THREAD

**Issue by oKess** [dbm-network/mods#377]
**Describe the bug**
In the await reaction action, the reaction is failing to be checked and the time limit is expired every time.

**To Reproduce**
https://prnt.sc/t3gzkw

**Expected behavior**
The expected behavior would be when reacting to the message, he skips the 2 actions of remove reaction and end action, but he is unable to check. In the beta version it works normally, only in v12 that doesn't work.

**Screenshots**
https://prnt.sc/t3gzkw
https://prnt.sc/t3gzto

**Comment by noahalma** [comment]
Alpha is the only version compatible with v12 afaik. Mods are currently being updated.

**Comment by oKess** [comment]
Yes, I know, but the action await reaction isn't working on alpha

> Alpha is the only version compatible with v12 afaik. Mods are currently being updated.

**Comment by LeonZ2019** [comment]
V12 actions is not ready yet, recommend downgrade to dbm beta for use the mod

**Comment by Almeeida** [comment]
On the javascript filter, `msg` is the message where the reaction is at, not the "command author".
you need to use Store Member Info - Member ID and use the temp variable there instead.

**Comment by oKess** [comment]
> On the javascript filter, `msg` is the message where the reaction is at, not the "command author".
> you need to use Store Member Info - Member ID and use the temp variable there instead.


But it is await reaction, it is not await response. In the beta version this normal script works.

**Comment by oKess** [comment]
And I also tested it that way and it didn't work.

**Comment by DevNoahh** [comment]
"Alpha is the only version compatible with v12 [afraid]. Mods are currently being updated."
"V12 actions is not ready yet, recommend downgrade to dbm beta for use the mod"
