### ISSUE TITLE
DBM ytdl-core Missing

### ISSUE THREAD

**Issue by BlainJudkins** [dbm-network/mods#393]
**Describe the bug**
Have the Github files in the action folder. Then started up DBM and added the commands to my bot, the goal of the Wub command is to play a specific Youtube video's audio in the voice chat. I added the Action#1 so that I would be able to see if the bot was trying to run the command when it was called. The Action#1 did post on the server, but then the bot does not join the voice channel, I looked at the logs and it gave the message below in the LOG section.

**To Reproduce**
1. Command c!Wub
2. Action#1       //        Send Message          //      Same Channel: "Wubs"
3. Action#2        //       Play Youtube Video    //    Youtube Link Here

**LOG**
Bot is ready!
DBM MODS (Node Module Installer v2.5) Attempting To Install Node Module: 'ytdl-core'. Please wait...
DBM MODS (Node Module Installer v2.5): Node Module 'ytdl-core' does not exist!
Command failed: npm install ytdl-core --loglevel=error --save

**Expected behavior**
Discord bot should be joining the server and be playing a specific Youtube video's audio.

**Comment by Mindlesscargo** [comment]
This is not a bug. Running `npm i ytdl-core` will install the module into your project.

**Comment by BlainJudkins** [comment]
Where do you run this at?

**Comment by Mindlesscargo** [comment]
Console

**Comment by BlainJudkins** [comment]
I run this in the Command Prompt and get this:

'npm' is not recognized as an internal or external command,
operable program or batch file.

**Comment by davipatricio** [comment]
Install node js

**Comment by BlainJudkins** [comment]
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\name\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\name\package.json'
npm WARN name No description
npm WARN name No repository field.
npm WARN name No README data
npm WARN name No license field.

+ ytdl-core@2.1.7
added 5 packages from 8 contributors and audited 5 packages in 0.646s
found 0 vulnerabilities

**Comment by xomega820** [comment]
Execute the command in the bot's project folder, not in user root folder.

**Comment by BlainJudkins** [comment]
Current 'Bot Log' Error:

Bot is ready!
DBM MODS (Node Module Installer v2.5) Attempting To Install Node Module: 'util'. Please wait...
DBM MODS (Node Module Installer v2.5): Node Module 'util' does not exist!
Command failed: npm install util --loglevel=error --save

**Comment by xomega820** [comment]
Ok, the same command but changing the `ytdl-core` with `util`.

**Comment by BlainJudkins** [comment]
Okay, the bot is no longer getting errors, but it is not joining the voice chat.

**Comment by xomega820** [comment]
You have the `ffmpeg-static` installed in package.json? Because the default ffmpeg that installs DBM doesn't work very well _(also doesn't work in linux)_, try installing that with `npm i ffmpeg-static --save` and retry.

**Comment by BlainJudkins** [comment]
I am using Windows, I tried doing "npm i ffmpeg-static --save" and got this:

`npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/derhuerst/http-basic.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\name\AppData\Roaming\npm-cache\_logs\2020-06-26T08_10_39_835Z-debug.log`

**Comment by xomega820** [comment]
Oh, you require `git` to install that, you need to install it from [here](https://git-scm.com/download/win), when you're done installing, run `git --version`, if you get something like: `git version xxxx.windows.x` you're done, otherwise, restart the computer. Then run `npm i ffmpeg-static --save` on the project.

**Comment by BlainJudkins** [comment]
I got all of that working, bot still is not joining the server. 

How do I add git to PATH?

**Comment by xomega820** [comment]
Hmm, if the bot does not join the voice channel, and does not give any error, it will be a problem with commands, try it with a command that is only "Join to Voice Channel", also check that the bot has perms to join.

The reason for adding **git** to PATH was to be 100% sure that it wouldn't give errors when executing the command.

**Comment by BlainJudkins** [comment]
I do not have a "Join to Voice Channel" command, only "Play Youtube Video"

**Comment by Almeeida** [comment]
https://discord.gg/3QxkZPK
