### ISSUE TITLE
The mod's action dont work

### ISSUE THREAD

**Issue by aroudo1111** [dbm-network/mods#419]
I dont know why, but when i try to execute some command that have any mod action (exemple: "Search on Youtube", "Generate a random work, ect...) the cmd say that action dont exist, like:

![buah](https://user-images.githubusercontent.com/67875615/86646413-26ea8900-bfd7-11ea-953a-9c3e8f2383b9.png)
 That's just one example.

I need some help, and in the support channel's on discord they dont answer me! Please
By the way, i am beginner, so i am asking if you can take it easy with me and try to explain with detail what i can do.
Thanks

**Comment by Almeeida** [comment]
Not a bug. Use the support channel in https://discord.gg/3QxkZPK
