### ISSUE TITLE
Store Json From WebAPI Problem

### ISSUE THREAD

**Issue by esteban003** [dbm-network/mods#420]
![image](https://user-images.githubusercontent.com/7058491/86672331-d551f680-bff6-11ea-8796-e68267d397f3.png)
![image](https://user-images.githubusercontent.com/7058491/86672402-e864c680-bff6-11ea-8e31-e80c4cd2aadc.png)
![image](https://user-images.githubusercontent.com/7058491/86672427-ee5aa780-bff6-11ea-8a36-7d989e8495a3.png)

I made a system to retrieve photos however it worked before at discordjs 11 and now since the maj nothing at all it does not find it while all the other sites find the way and it worked before I was on discord we did not know how to help me thank you in advance.

**Comment by RigidStudios** [comment]
Yup I can verify this, going to the URL in a browser returns JSON Data.

**Comment by esteban003** [comment]
https://e621.net/posts.json?tags=fur+type:png+order%3Arandom+rating%3Aexplicit&limit=1

**Comment by esteban003** [comment]
{"error":"No JSON Data Returned","statusCode":0}

**Comment by Almeeida** [comment]
Cannot reproduce. I believe your path is incorrect.

Tested with this setup:
![image1](https://i.imgur.com/uY6yWYL.png)
Same URL as you sent, `posts[0].file.url` as the path.

**Comment by RigidStudios** [comment]
Your JSON Path is messed up; `$.posts[0].file.url` would work.

**Comment by esteban003** [comment]
Ok Thanks
