### ISSUE TITLE
The "Check Variable" action is bugged, when I use the "True or False" factors it only pays attention to the "False"

### ISSUE THREAD

**Issue by Noctaletz** [dbm-network/mods#428]
This bug needs to be fixed, I don't know if it only happens to me or everyone
But this action is important, so I would like to know why this error arises

My English is bad, so I can't specify much about this problem

Command Rawdata for testing: https://pastebin.com/4uZZ8SCH

**Images:**
![dzgfhxjhgc](https://user-images.githubusercontent.com/46089960/86868661-8a45eb00-c0ab-11ea-8b4e-5c7d15a3ee25.png)
![dxhxdhgxfhj](https://user-images.githubusercontent.com/46089960/86868668-8b771800-c0ab-11ea-8d13-d1209710a907.png)

 hope I'm not misusing the system

**Comment by Almeeida** [comment]
Await Response stores a Message (or a list of Messages if the max is >1).
That means you must store the content of the message, for example, by using the Store Message Info action and selecting the Message Content option and then use the variable from there in the Check Variable action.

*You also have outdated mods. [Installation Guide](https://github.com/dbm-network/mods#downloads)*
