### ISSUE TITLE
Check Member data does not work in events

### ISSUE THREAD

**Issue by mrbell11** [dbm-network/mods#439]
**Describe the bug**
When you try to check member data in events the bot will always default to false even if the result is true.

**To Reproduce**
1. Create a event with the event trigger being "Member Update"
2. We will name Before trigger "before" and after trigger "after"
3. We will then set the event up so that it will post in a channel when it is triggered.
4.  Now we want to add Store member info for both "before" and "after" and we want to store "Member Avatar URL"
5. We will store member avatar URL "before" as "before-avatar" and member avatar URL "after" as "after-avatar"
5. Then we want to check member data for the member"after" with the data name "${tempVars("before-avatar")}"
6. We would make the comparison type equals.
7. then set the compare value to "tempVars("after-avatar")"
8. We set the if true then "stop action sequence"
9. Then set if False to "continue action"
10. Then have the send message under the check member info

**Expected behavior**
I expected the bot to only post if a user updates there profile picture. Instead the bot will post anything a user updates anything on there profile, such as there username, or there discriminator.

**Screenshots**
https://i.imgur.com/jXssFka.png
https://i.imgur.com/z0XQpw7.png
https://i.imgur.com/bQd9Kpg.png
https://i.imgur.com/7XAD1ZH.png

**Comment by LeonZ2019** [comment]
not a bug, you have misunderstand what is member update event for, please use user update

**Comment by mrbell11** [comment]
There is no user update?

**Comment by RigidStudios** [comment]
The events repo can be found [here](https://github.com/dbm-network/events). Avatar Updates don't trigger Member Update.

**Comment by mrbell11** [comment]
Weird, I get absolutely nothing now

**Comment by noahalma** [comment]
Member data is deprecated
