### ISSUE TITLE
Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.

### ISSUE THREAD

**Issue by Benjamina8475** [dbm-network/mods#446]
Hello,

Since not much time I have this error, I have searched on the internet for things but without success I would like to know if there is a patch or an explanation so that I can fix the problem? Thank you in advance for the answer

![image](https://user-images.githubusercontent.com/68239939/87324491-71688a00-c530-11ea-83a7-206eb1c92560.png)

**Comment by DevNoahh** [comment]
I am also having the same issue.

**Comment by Almeeida** [comment]
Does this error occur when hosting the bot via your computer? Also, what are you using to host the bot?

**Comment by Benjamina8475** [comment]
It does it to me on the computer or host I tested 3 hosters it's from the new Discord.js that it does it to me, I have google cloud, inovaperf and curse hosting it's all debian even my raspberry does it to me too...

**Comment by Benjamina8475** [comment]
> Does this error occur when hosting the bot via your computer? Also, what are you using to host the bot?

It does it to me on the computer or host I tested 3 hosters it's from the new Discord.js that it does it to me, I have google cloud, inovaperf and curse hosting it's all debian even my raspberry does it to me too...

**Comment by DevNoahh** [comment]
> 
> 
> Does this error occur when hosting the bot via your computer? Also, what are you using to host the bot?

Both on my VPS and on my Local Machine. Both when using Ubuntu and Windows, and both when using `node bot.js` and `forever start bot.js`

**Comment by ForceBlood** [comment]
This issue doesn't have anything to do with mods. This issue can occur if you have a slow/unstable connection with discord and if you are using the free tier of google cloud and etc. they probably give pretty slow connection and that might be the issue.

**Comment by Benjamina8475** [comment]
No and no at google I took a machine that costs me a bar and I changed 4 times host, moreover even on my computer it does this to me is if it's my connection is more fiber that is needed it's the internet of NASA I do 111 GB in 1 hour of downloading ... so that's not the problem

**Comment by ForceBlood** [comment]
Even if the problem isn't from your internet it's still an error event sent from discord which we can do nothing about.

**Comment by DevNoahh** [comment]
So basically there's nothing to do to combat this right now...

**Comment by davipatricio** [comment]
Not an issue with mods
