### ISSUE TITLE
Run SQL Query

### ISSUE THREAD

**Issue by pedro-dts** [dbm-network/mods#452]
**Describe the bug**
A problem with mysql connection

**To Reproduce**
I Just run sql query, get connection valid on "Check", then in query for example i put this UPDATE `kpaneldt_dts`.`users` SET `whitelisted`='2' WHERE  `id`=3; 
It executes the UPDATE and changes in DB but don´t jump to the next action sending this error in console

**Screenshots**
![error](https://user-images.githubusercontent.com/68306227/87485785-811bc780-c631-11ea-992e-df77137e966e.png)

**Comment by Synozis** [comment]
I have the same problems, but my error is this:

`Bot has started at Wednesday, Jul 15, 2020, 4:51:33 PM
? Error with the command "Run SQL Query", Action #4:
? TypeError: this.getMods is not a function
?`

**Comment by Almeeida** [comment]
https://github.com/dbm-network/mods/pull/453 might have fixed your problem @pedro-dts 
Please, try updating your mods ([guide](https://github.com/dbm-network/mods#downloads)) and see if it works

**Comment by Almeeida** [comment]
@Synozis use the support channel in our [Discord server](https://discord.gg/3QxkZPK) instead please.

**Comment by pedro-dts** [comment]
@Almeeida Another error but this one is based on previous 
![Screenshot_5](https://user-images.githubusercontent.com/68306227/87578833-eb357a80-c6cc-11ea-8119-e0bb6496a982.png)

**Comment by Synozis** [comment]
i'm saying some message in Discord, but i don't have any response. Can i have a solution for this error ? 
My database is valid and tested, but this error does not allow the bot to output the desired data. The concern is that with this error, the bot is unusable. And it makes me this mistake with several versions of DMB Mod

**Comment by Almeeida** [comment]
Perhaps this new pull request https://github.com/dbm-network/mods/pull/455 has fixed the issue.
Please test it and give feedback. 
/cc @pedro-dts

**Comment by Almeeida** [comment]
Since nobody replied, I will assume this issue has been fixed.
