### ISSUE TITLE
No docs documentation for a lot of mods

### ISSUE THREAD

**Issue by TheSalvy** [dbm-network/mods#458]
Hello there

So there used to be a channel in the support server called beta mods, in that channel developer who made new mods used to introduce the mod and tell everyone how does it work.

Now a lot of mods are kind of impossible to use, for example how to use blocklist mod or audit log mod?

I think it's good to bring back that channel and for the download link redirect them to the repo.

**Comment by Almeeida** [comment]
We are working on something similar, https://github.com/dbm-network/mods/blob/master/docs/mods.json
