### ISSUE TITLE
Run SQL Query (outputs double)

### ISSUE THREAD

**Issue by theQuery** [dbm-network/mods#462]
right now the Run SQL Query action is outputting the result double.
say there's a table _"xpandlevels"_ structured with the columns _"id, xp, level"_ with the values _(454217004841435136, 5403, 7)_

example:
if this query is run _"select xp FROM xpandlevels WHERE id = 454217004841435136;"_ then it outputs _[5403, 5403]_, although its only supposed to output _[5403]_

EDIT:
it outputs quadruple if its stored with _$..*_, and double when its stored with _$..xp_
when it outputs quadruple it does it like this: _[[{"xp":5403}],[{"xp":5403}],{"xp":5403},{"xp":5403}]_

EDIT 2:
this only happens when "select" is written as "select" and not "SELECT" (capital letters)

**Comment by TheSalvy** [comment]
I have the same issue

**Comment by LeonZ2019** [comment]
Why did you use lower case?

**Comment by theQuery** [comment]
> Why did you use lower case?

i was quickly typing a query to test something and then stumbled upon it. im sure it isnt supposed to be like this though, hence a bug
