### ISSUE TITLE
Store member info doesn't work with events.

### ISSUE THREAD

**Issue by F4LS3T** [dbm-network/mods#469]
# **Describe the bug**

Store member info doesn't work with events. No matter if used with prior or after [Member voice update trigger]

# **To Reproduce**

1. PASTE RAWDATA:

https://pastebin.com/M3pGPm3W

# **Expected behavior**

I expect bot to detect correctly which voice channel is user now

**Comment by Thaliruth1** [comment]
So there you create another account just to be able to answer here, but then you see that it does not really bring you much to block users, for whatever reason I became it!

but anyway to the topic
I can NOT confirm this bug. All my events where Store member info is present are running without problems with Discord v12 and Node 12.18.2 and Node 14.6.0

Therefore I think that this is rather a user bug.
