### ISSUE TITLE
Store Member info doesn't work with events (Voice Member Update).

### ISSUE THREAD

**Issue by Maciekrybka009** [dbm-network/mods#504]
**Describe the bug**
Store Member info doesn't work with events (Voice Member Update).
Got this error on my main bot. I created a new bot and the same error shows up.

**To Reproduce**
1. Create voice member event.
2. Store member info - Display name.
3. Send the variable.
Variable will show as undefined.

**Expected behavior**
Bot should've sent nickname of the player who joined the VC.

**Screenshots**
1 . https://gyazo.com/1560430936885fb83a2f2657a8e1d494
2. https://gyazo.com/92cfcc5fbfa4dd0c7f8fa8bf5d554c88
3. https://gyazo.com/d950e4ba73bb33b1995edb56cc3b8e3c

**Comment by Maciekrybka009** [comment]
I would like to add it all worked perfectly on Beta before that version was released to main DBM.

**Comment by TheMonDon** [comment]
I can confirm this issue but the title is incorrect.
The member voice update event throws out VoiceState instead of member now. You will have to use find member
with tempVars("user1").id, that will give you the actual member.

**Comment by Maciekrybka009** [comment]
How to do it?
Also Find Member Mod doesn't work and gives this error.
https://gyazo.com/5b35b6a83004ed138dd55544bc2fd0df

**Comment by RigidStudios** [comment]
Voice Member Update is not an event managed by this repo, it's a DBM Original event.

**Comment by TheMonDon** [comment]
Closing this issue as it's not an actual bug it's just how the event works, and a solution has been given.
