### ISSUE TITLE
YouTube Info gives title as undefined

### ISSUE THREAD

**Issue by dexthearcticfox** [dbm-network/mods#505]
**Describe the bug**
The YouTube info mod gives "undefined as the title of videos.

**To Reproduce**
1. Get video title from store youtube info action
2. See video title sent as undefined

**Expected behavior**
It should give the correct video title from a youtube video.

**Screenshots**
![undefined](https://user-images.githubusercontent.com/34548396/89172592-ce2cf280-d57a-11ea-859b-6fae71fe3da1.PNG)

**Comment by TheMonDon** [comment]
I'll look into this.

**Comment by TheMonDon** [comment]
I can't replicate this issue at all. Did you check your console for errors?

**Comment by dexthearcticfox** [comment]
Yes. There were no errors and two other people said they have the same problem on the dbm network discord server.

**Comment by dexthearcticfox** [comment]
I'm not sure what happened but it is now working. Very odd.
