### ISSUE TITLE
Audit Log List Error

### ISSUE THREAD

**Issue by savascipower** [dbm-network/mods#510]
Store Audit Log List says executor undefined in Create Channel.

**Comment by RigidStudios** [comment]
@almeidx You transfered this from dbm-network/extensions so it should be given the extensions label.
@savascipower Do all the other audit log actions say executor undefined, or just Create Channel? Also, any other undefined infos?

**Comment by TheMonDon** [comment]
I'm closing this issue as you've not replied to the last request for more information, if you're still having issues feel free to ask in the support channels.
