### ISSUE TITLE
Store Current Voice Channel

### ISSUE THREAD

**Issue by kaaax0815** [dbm-network/mods#521]
**Is your feature request related to a problem? Please describe.**
I want to check if nobody else is in the bots vc, if true than the bot should disconnect
But the problem is i find no solution where i can get the current voice channel of the bot as a variable

**Describe the ideal solution**
Create a new action called "Store Current Voice Channel" or so. there you can create a variable

**Describe alternatives you've considered**
I cant find any alternatives

**Comment by RediPanda** [comment]
Get Bot as Member
Store Member Info -> Member Voice Channel
