### ISSUE TITLE
Run SQL Query - Broken

### ISSUE THREAD

**Issue by Regado** [dbm-network/mods#523]
When you put sqlite, the address found in the database, when you turn on the bot, it appears the module `sqlite3` that is not installed, and I already installed it through the Module Manager! (I also went to the modules folder to see if I had the `sqlite3` folder, and it was there, however, from the console error.)

**Comment by RigidStudios** [comment]
@Regado Could you show the console error?

**Comment by Regado** [comment]
> @Regado Could you show the console error?

Starting bot at version: "1.6.9"
 > Multiple Bot Owners Extension Loaded!
 ? npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
 ? npm WARN deprecated har-validator@5.1.5: this library is no longer supported
 ? npm WARN discord.js@12.2.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord.js@12.2.0 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord.js@12.2.0 requires a peer of libsodium-wrappers@^0.7.6 but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord.js@12.2.0 requires a peer of sodium@^3.0.2 but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord.js@12.2.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord.js@12.2.0 requires a peer of zlib-sync@^0.1.6 but none is installed. You must install peer dependencies yourself.
 ? npm WARN prism-media@1.2.2 requires a peer of ffmpeg-static@^2.4.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
 ? npm WARN prism-media@1.2.2 requires a peer of @discordjs/opus@^0.1.0 but none is installed. You must install peer dependencies yourself.
 ? npm WARN prism-media@1.2.2 requires a peer of node-opus@^0.3.1 but none is installed. You must install peer dependencies yourself.
 ? npm WARN prism-media@1.2.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
 ? npm WARN ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
 ? npm WARN ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord-bot-maker-bot@1.6.8 No description
 ? npm WARN discord-bot-maker-bot@1.6.8 No repository field.
 ? npm WARN discord-bot-maker-bot@1.6.8 No license field.
 ? 
 ? npm ERR! path C:\Users\Lenovo\Downloads\BotsDBM\Music\node_modules\.bin\semver.cmd
 ? npm ERR! code EEXIST
 ? npm ERR! Refusing to delete C:\Users\Lenovo\Downloads\BotsDBM\Music\node_modules\.bin\semver.cmd: is outside C:\Users\Lenovo\Downloads\BotsDBM\Music\node_modules\semver and not a link
 ? npm ERR! File exists: C:\Users\Lenovo\Downloads\BotsDBM\Music\node_modules\.bin\semver.cmd
 ? npm ERR! Move it away, and try again.
 ? 
 ? npm ERR! A complete log of this run can be found in:
 ? npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2020-08-18T17_27_45_174Z-debug.log
 ? 
 > SQL Mod Error: Error: Cannot find module 'C:\Users\Lenovo\Downloads\BotsDBM\Music\node_modules\sqlite3\lib\binding\napi-v3-win32-ia32\node_sqlite3.node'
 > Require stack:
 > - C:\Users\Lenovo\Downloads\BotsDBM\Music\node_modules\sqlite3\lib\sqlite3-binding.js
 > - C:\Users\Lenovo\Downloads\BotsDBM\Music\node_modules\sqlite3\lib\sqlite3.js
 > - C:\Users\Lenovo\Downloads\BotsDBM\Music\actions\aaa_dbmmods_dependencies_MOD.js
 > - C:\Users\Lenovo\Downloads\BotsDBM\Music\bot.js
 >     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
 >     at Function.Module._load (internal/modules/cjs/loader.js:864:27)
 >     at Module.require (internal/modules/cjs/loader.js:1044:19)
 >     at require (internal/modules/cjs/helpers.js:77:18)
 >     at Object.<anonymous> (C:\Users\Lenovo\Downloads\BotsDBM\Music\node_modules\sqlite3\lib\sqlite3-binding.js:4:15)
 >     at Module._compile (internal/modules/cjs/loader.js:1158:30)
 >     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
 >     at Module.load (internal/modules/cjs/loader.js:1002:32)
 >     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
 >     at Module.require (internal/modules/cjs/loader.js:1044:19)
 ? (node:14744) UnhandledPromiseRejectionWarning: Error: Command failed: npm i sqlite3
 ? npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
 ? npm WARN deprecated har-validator@5.1.5: this library is no longer supported
 ? npm WARN discord.js@12.2.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord.js@12.2.0 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord.js@12.2.0 requires a peer of libsodium-wrappers@^0.7.6 but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord.js@12.2.0 requires a peer of sodium@^3.0.2 but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord.js@12.2.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord.js@12.2.0 requires a peer of zlib-sync@^0.1.6 but none is installed. You must install peer dependencies yourself.
 ? npm WARN prism-media@1.2.2 requires a peer of ffmpeg-static@^2.4.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
 ? npm WARN prism-media@1.2.2 requires a peer of @discordjs/opus@^0.1.0 but none is installed. You must install peer dependencies yourself.
 ? npm WARN prism-media@1.2.2 requires a peer of node-opus@^0.3.1 but none is installed. You must install peer dependencies yourself.
 ? npm WARN prism-media@1.2.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
 ? npm WARN ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
 ? npm WARN ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord-bot-maker-bot@1.6.8 No description
 ? npm WARN discord-bot-maker-bot@1.6.8 No repository field.
 ? npm WARN discord-bot-maker-bot@1.6.8 No license field.
 ? 
 ? npm ERR! path C:\Users\Lenovo\Downloads\BotsDBM\Music\node_modules\.bin\semver.cmd
 ? npm ERR! code EEXIST
 ? npm ERR! Refusing to delete C:\Users\Lenovo\Downloads\BotsDBM\Music\node_modules\.bin\semver.cmd: is outside C:\Users\Lenovo\Downloads\BotsDBM\Music\node_modules\semver and not a link
 ? npm ERR! File exists: C:\Users\Lenovo\Downloads\BotsDBM\Music\node_modules\.bin\semver.cmd
 ? npm ERR! Move it away, and try again.
 ? 
 ? npm ERR! A complete log of this run can be found in:
 ? npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2020-08-18T17_27_45_174Z-debug.log
 ? 
 ?     at checkExecSyncError (child_process.js:630:11)
 ?     at Object.execSync (child_process.js:666:15)
 ?     at C:\Users\Lenovo\Downloads\BotsDBM\Music\actions\aaa_dbmmods_dependencies_MOD.js:6:32
 ?     at new Promise (<anonymous>)
 ?     at Object.installModule (C:\Users\Lenovo\Downloads\BotsDBM\Music\actions\aaa_dbmmods_dependencies_MOD.js:5:12)
 ?     at Object.require (C:\Users\Lenovo\Downloads\BotsDBM\Music\actions\aaa_dbmmods_dependencies_MOD.js:19:12)
 ?     at getType (C:\Users\Lenovo\Downloads\BotsDBM\Music\actions\run_sql_query_MOD.js:351:16)
 ?     at Object.action [as Run SQL Query] (C:\Users\Lenovo\Downloads\BotsDBM\Music\actions\run_sql_query_MOD.js:367:18)
 ?     at Object.Actions.invokeEvent (C:\Users\Lenovo\Downloads\BotsDBM\Music\bot.js:524:18)
 ?     at Object.Events.onInitialization (C:\Users\Lenovo\Downloads\BotsDBM\Music\bot.js:1012:13)
 ? (node:14744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
 ? (node:14744) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 ? 
 ? npm WARN discord.js@12.2.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord.js@12.2.0 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord.js@12.2.0 requires a peer of libsodium-wrappers@^0.7.6 but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord.js@12.2.0 requires a peer of sodium@^3.0.2 but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord.js@12.2.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord.js@12.2.0 requires a peer of zlib-sync@^0.1.6 but none is installed. You must install peer dependencies yourself.
 ? npm WARN prism-media@1.2.2 requires a peer of ffmpeg-static@^2.4.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
 ? npm WARN prism-media@1.2.2 requires a peer of @discordjs/opus@^0.1.0 but none is installed. You must install peer dependencies yourself.
 ? npm WARN prism-media@1.2.2 requires a peer of node-opus@^0.3.1 but none is installed. You must install peer dependencies yourself.
 ? npm WARN prism-media@1.2.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
 ? npm WARN ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
 ? npm WARN ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord-bot-maker-bot@1.6.8 No description
 ? npm WARN discord-bot-maker-bot@1.6.8 No repository field.
 ? npm WARN discord-bot-maker-bot@1.6.8 No license field.
 ? 
 ? npm ERR! path C:\Users\Lenovo\Downloads\BotsDBM\Music\node_modules\.bin\semver.cmd
 ? npm ERR! code EEXIST
 ? npm ERR! Refusing to delete C:\Users\Lenovo\Downloads\BotsDBM\Music\node_modules\.bin\semver.cmd: is outside C:\Users\Lenovo\Downloads\BotsDBM\Music\node_modules\semver and not a link
 ? npm ERR! File exists: C:\Users\Lenovo\Downloads\BotsDBM\Music\node_modules\.bin\semver.cmd
 ? npm ERR! Move it away, and try again.
 ? 
 ? npm ERR! A complete log of this run can be found in:
 ? npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2020-08-18T17_28_00_662Z-debug.log
 ? 
 > SQL Mod Error: Error: Cannot find module 'mysql2'
 > Require stack:
 > - C:\Users\Lenovo\Downloads\BotsDBM\Music\actions\aaa_dbmmods_dependencies_MOD.js
 > - C:\Users\Lenovo\Downloads\BotsDBM\Music\bot.js
 >     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
 >     at Function.Module._load (internal/modules/cjs/loader.js:864:27)
 >     at Module.require (internal/modules/cjs/loader.js:1044:19)
 >     at require (internal/modules/cjs/helpers.js:77:18)
 >     at Object.require (C:\Users\Lenovo\Downloads\BotsDBM\Music\actions\aaa_dbmmods_dependencies_MOD.js:20:14)
 >     at getType (C:\Users\Lenovo\Downloads\BotsDBM\Music\actions\run_sql_query_MOD.js:339:16)
 >     at Object.action [as Run SQL Query] (C:\Users\Lenovo\Downloads\BotsDBM\Music\actions\run_sql_query_MOD.js:367:18)
 >     at Object.Actions.callNextAction (C:\Users\Lenovo\Downloads\BotsDBM\Music\bot.js:547:18)
 >     at Object.action [as Store Member Info] (C:\Users\Lenovo\Downloads\BotsDBM\Music\actions\store_member_info.js:371:8)
 >     at Object.Actions.invokeActions (C:\Users\Lenovo\Downloads\BotsDBM\Music\bot.js:502:18)
 ? (node:14744) UnhandledPromiseRejectionWarning: Error: Command failed: npm i mysql2
 ? npm WARN discord.js@12.2.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord.js@12.2.0 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord.js@12.2.0 requires a peer of libsodium-wrappers@^0.7.6 but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord.js@12.2.0 requires a peer of sodium@^3.0.2 but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord.js@12.2.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord.js@12.2.0 requires a peer of zlib-sync@^0.1.6 but none is installed. You must install peer dependencies yourself.
 ? npm WARN prism-media@1.2.2 requires a peer of ffmpeg-static@^2.4.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
 ? npm WARN prism-media@1.2.2 requires a peer of @discordjs/opus@^0.1.0 but none is installed. You must install peer dependencies yourself.
 ? npm WARN prism-media@1.2.2 requires a peer of node-opus@^0.3.1 but none is installed. You must install peer dependencies yourself.
 ? npm WARN prism-media@1.2.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
 ? npm WARN ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
 ? npm WARN ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
 ? npm WARN discord-bot-maker-bot@1.6.8 No description
 ? npm WARN discord-bot-maker-bot@1.6.8 No repository field.
 ? npm WARN discord-bot-maker-bot@1.6.8 No license field.
 ? 
 ? npm ERR! path C:\Users\Lenovo\Downloads\BotsDBM\Music\node_modules\.bin\semver.cmd
 ? npm ERR! code EEXIST
 ? npm ERR! Refusing to delete C:\Users\Lenovo\Downloads\BotsDBM\Music\node_modules\.bin\semver.cmd: is outside C:\Users\Lenovo\Downloads\BotsDBM\Music\node_modules\semver and not a link
 ? npm ERR! File exists: C:\Users\Lenovo\Downloads\BotsDBM\Music\node_modules\.bin\semver.cmd
 ? npm ERR! Move it away, and try again.
 ? 
 ? npm ERR! A complete log of this run can be found in:
 ? npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2020-08-18T17_28_00_662Z-debug.log
 ? 
 ?     at checkExecSyncError (child_process.js:630:11)
 ?     at Object.execSync (child_process.js:666:15)
 ?     at C:\Users\Lenovo\Downloads\BotsDBM\Music\actions\aaa_dbmmods_dependencies_MOD.js:6:32
 ?     at new Promise (<anonymous>)
 ?     at Object.installModule (C:\Users\Lenovo\Downloads\BotsDBM\Music\actions\aaa_dbmmods_dependencies_MOD.js:5:12)
 ?     at Object.require (C:\Users\Lenovo\Downloads\BotsDBM\Music\actions\aaa_dbmmods_dependencies_MOD.js:19:12)
 ?     at getType (C:\Users\Lenovo\Downloads\BotsDBM\Music\actions\run_sql_query_MOD.js:339:16)
 ?     at Object.action [as Run SQL Query] (C:\Users\Lenovo\Downloads\BotsDBM\Music\actions\run_sql_query_MOD.js:367:18)
 ?     at Object.Actions.callNextAction (C:\Users\Lenovo\Downloads\BotsDBM\Music\bot.js:547:18)
 ?     at Object.action [as Store Member Info] (C:\Users\Lenovo\Downloads\BotsDBM\Music\actions\store_member_info.js:371:8)
 ? (node:14744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
 ?

**Comment by shootdot** [comment]
@Regado First goto your bot directory and open cmd over there and type `npm install`. After the process ends type `npm i mysql2`
After this process also if the error occurs send your error log here
**Note** npm warn will not cause any problem or crash to your bot
