### ISSUE TITLE
Store Time Info Text

### ISSUE THREAD

**Issue by master3395** [dbm-network/mods#525]
Hello, if i chose "Month Text", it shows up as "undefined" in dbm, it does function as it should.
just a small text error.

![1](https://user-images.githubusercontent.com/4199669/89681408-32421480-d8f5-11ea-9554-0617d7d3022a.JPG)

![2](https://user-images.githubusercontent.com/4199669/89681407-3110e780-d8f5-11ea-835e-ea48b84da5ff.JPG)

**Comment by shootdot** [comment]
It is a default command still let me upload in PR

**Comment by almeidx** [comment]
A fixed version has been sent to the developer and the app will be updated soon, thanks for pointing it out.
