### ISSUE TITLE
Bot leaves vc after song is finished playing

### ISSUE THREAD

**Issue by kaaax0815** [dbm-network/mods#531]
**Describe the bug**
After the bot has finished the songs, he disconnects

**To Reproduce**
1. Make a play commands with youtube search
2. Let the bot finish the song
3. bot disconnects

**Expected behavior**
Bot should stay in vc until i say so

**Comment by TheRealPikachu** [comment]
is this a bug not minimodding

**Comment by kaaax0815** [comment]
It is unexpected behaviour

**Comment by almeidx** [comment]
Incorrect. That's expected behaviour.

**Comment by kaaax0815** [comment]
No because my expected behaviour is that the bot stays in the vc

**Comment by almeidx** [comment]
The default behaviour of DBM bots is to leave the voice channel after it stops playing. **This is not a bug.**
