### ISSUE TITLE
Stay in VC after song

### ISSUE THREAD

**Issue by kaaax0815** [dbm-network/mods#533]
Because this is not a bug, i request a feature or a work-around.

**Is your feature request related to a problem? Please describe.**
If i play a song and the song finishes, the bot leaves vc

**Describe the ideal solution**
Yeah, the bot should stay in vc

**Additional context**
i dont have an afk timer

**Comment by TheMonDon** [comment]
Here is a quick run script EVENT that will have the bot stay in the voice channel. 
https://pastebin.com/k1Pbfde5
