### ISSUE TITLE
Spotify Search Mod Doesn't Work

### ISSUE THREAD

**Issue by TheMonDon** [dbm-network/mods#534]
**Describe the bug**
the node-module that the Spotify search mod uses has not been updated in 2 years so I can guarantee the people saying it doesn't work are correct. I do not want to update this mod but am making an issue request with possible solutions:

1.Find someone to maintain said mod
2. Delete the mod as it's not very useful if no one cares to maintain it.

**Comment by shootdot** [comment]
Hi @TheMonDon 
I shall maintain this mod

**Comment by TheRealPikachu** [comment]
Looks like Shoot will handle this one, peace

**Comment by TheRealPikachu** [comment]
if shoot is going to maintain / make changes to this mod, can it be closed?

**Comment by RaiRoblox** [comment]
mo

**Comment by kindkidbots** [comment]
please fix this, I need this for my bot.

**Comment by TheMonDon** [comment]
"Fixed" in #678
