### ISSUE TITLE
Change Server / Check if Member has Role

### ISSUE THREAD

**Issue by theQuery** [dbm-network/mods#536]
**Describe the bug**
the "Check If Member has Role" action doesnt recognize the changing of servers when using the "Change Server" action, even though the bot is in both servers

**To Reproduce**
1. Use this raw data that I made for testing it: https://pastebin.com/raw/hzKGZqQ1
2. Change the server ID in "Find Server" to the ID of **server A** and change the role ID in "Find Role" to the ID of a role in **server A**
3. Assign the said role to yourself in **server A**
4. Send the command in another server (**server B**) to check if you have the role in **server A**
5. You will see that it says you do not have the role even when its supposed to say that you do have the role

**Expected behavior**
the bot is supposed to say that you do have the role in **server A** even when you run the command in **server B**

**Comment by RigidStudios** [comment]
Can't find Check if Member has Role in the repo, it's probably a default action.

**Comment by RigidStudios** [comment]
@almeidx Not a mod, you can close this.
