### ISSUE TITLE
Run SQL Query

### ISSUE THREAD

**Issue by loganout** [dbm-network/mods#564]
Hello,
**Run SQL Query** always run four times.
![unknown](https://user-images.githubusercontent.com/4658212/91066394-0e2a4700-e608-11ea-8abe-4a901db1ba00.png)

I have a database where I store server members' reminders.
Due to this problem in the mod, members are being mentioned four times as well.
![Screenshot_3](https://user-images.githubusercontent.com/4658212/91066823-8a248f00-e608-11ea-9977-ca5dab2fb127.png)

I need do a member reminder Timestamp check with the On Interval trigger every X seconds. I have 4 test servers so it makes four connections ... imagine if I put this in my bot that is on more than 100 servers. lol

**Comment by DetroitWhiskey136** [comment]
That sounds like your not using the Run Action Sequence Once action in the command/event

**Comment by DetroitWhiskey136** [comment]
theres a option in the action to Run Once: Globally, very useful for pesky such tasks
