### ISSUE TITLE
Issue with Send Embed Message

### ISSUE THREAD

**Issue by ryando123** [dbm-network/mods#567]
**Describe the bug**
The problem I'm having is with the send embed message action. It seems to be ignoring the Source Embed Object temp variable.

**To Reproduce**
1. Create a normal embed message
2. When coming to the Send To: part put it on a server variable.
3. Try to find your embed temp variable in the Source Embed Object part

**Expected behavior**
The bot won't be able to find the variable.

**Screenshots**
![image](https://user-images.githubusercontent.com/25272264/91320969-6e62e980-e7be-11ea-8379-f4e351e6c180.png)
Here you can see the variable doesn't show up.

![image](https://user-images.githubusercontent.com/25272264/91321015-7cb10580-e7be-11ea-8dd9-508e9ee92a45.png)
When changing the Send To: part to a temp variable it shows up

**Comment by RigidStudios** [comment]
Would this be the same thing as #315 ?

**Comment by ryando123** [comment]
Yea, doesn't seem to be fixed I assume.

**Comment by TheMonDon** [comment]
Looks like this should have been fixed as this was a duplicate of #315.
