### ISSUE TITLE
Issue when changing volume

### ISSUE THREAD

**Issue by kaaax0815** [dbm-network/mods#568]
**Describe the bug**
Cant get current volume, only says volume = 50%

**To Reproduce**
1. get current volume (50%)
2. change volume (100%)
3. get current volume (still 50%) (real volume 100% tho)

**Expected behaviour**
Its should say 100% because i changed it to 100% but it doenst...

**Edit**
The error occurs only when bot is not playing anything, because then its not changing volume, whyever

**Edit2**
the error occurs when changing when setting to anyvolume instead of 50 or 100
example: change from 100 to 80
get volume result: 50

**Edit3**
dont get the error with 5000 volume

**Comment by TheMonDon** [comment]
I'm going to close this issue as that is something on how the default DBM works if you're not in a voice channel/nothing is playing. This has nothing to do with mods.
