### ISSUE TITLE
Mod "Set Channel Permissions" conflicting with Default Action

### ISSUE THREAD

**Issue by Lucasamiel0406** [dbm-network/mods#569]
**Describe the bug**
~~The mod `Set Channel Permissions` on the `Permissions Category` conflict with/replaces the Default Action with the same name on `Channel Category` who set X permission for everyone on X channel, and because of this you can't set X permission for everyone on a channel (the `Permissions Category` one exiges a member or role) and also many people are complaining that Lock/Unlock rawdatas isn't working anymore
For now we only have `Set Voice Permissions` who set X permission for everyone on X voice channel.~~

Update v1.1: Now the issue is "TheMonDon friendly".

> The new Set Channel Permissions replaces the old one that changes permissions for `@EVERYONE` instead of a role or member in a channel, because of all this, many rawdatas are broken now.
Still don't understand? Open `Set Voice Channel Permissions` action and then `Set Channel Permissions`, one change perms for role/member and the other for the role `@EVERYONE`, that's what I'm trying to say.

**Comment by TheMonDon** [comment]
I am very confused by your description can you re-format what you're trying to say if this is still an issue?

**Comment by master3395** [comment]
I think he means that one of the actions conflicts with default actions in DBM.
There seem to be several actions you can use, but if they were merged into 1, we would not need to have too many actions to maintain.

![image](https://user-images.githubusercontent.com/4199669/98483686-b4025080-220a-11eb-88ee-99d501712d68.png)

**Comment by DetroitWhiskey136** [comment]
I do agree all the channel perms mods should be merged into one but that would make problems for people already using the existing mods when they update.

**Comment by Fisheiyy** [comment]
maybe use a type field at first just to select which permission to change; just use the code that is already made for them just behind a selection field for all the different types

**Comment by Lucasamiel0406** [comment]
Issue updated 👍
