### ISSUE TITLE
Dashboard Extension ID

### ISSUE THREAD

**Issue by master3395** [dbm-network/mods#571]
Hello, i have encountered a property issue.
It shows up as undefined.
And i do know that i have defined it.

![image](https://user-images.githubusercontent.com/4199669/91774906-24c53500-ebea-11ea-9cfd-ab1ec480f37c.png)

![image](https://user-images.githubusercontent.com/4199669/91774793-ed568880-ebe9-11ea-84f1-b593db22ed7f.png)

**Comment by TheMonDon** [comment]
Closing this issue as the author has stated it does not currently work.
