### ISSUE TITLE
Delete Server Data - action not functioning

### ISSUE THREAD

**Issue by Ryckie** [dbm-network/mods#578]
**Describe the bug**
The Delete Server Data action does not delete a defined server data. In fact, it seems to be doing nothing. There is no console error.

**To Reproduce**
1. Have at least 1 server data;
2. Try to delete it with the Delete Server Data action;
3. Check the serverVars.json file, nothing has changed.

**Expected behavior**
I expect this action to remove a defined server data out of the server serverVars.json file.

**Comment by JasperEdits** [comment]
The file that should be updated is "servers.json" but yeah, it's not deleting the data anyways.

**Comment by DetroitWhiskey136** [comment]
This bug should be resolved shortly, refer to #593 for more information on its status
