### ISSUE TITLE
Presence Update | temp variables return empty object

### ISSUE THREAD

**Issue by Ryckie** [dbm-network/mods#579]
**Describe the bug**
The Event Trigger __Presence Update__ event trigger can store the member prior and member after the presence update was triggered. No actions are able to work, I believe the reason is because it stores the member as **[object Object]**.

**To Reproduce**
1. Go to Events
2. Use event trigger 'Presence Update'
3. define the 'Temp Variable Name (stores member prior to their presence update):'.
4. add the action 'send message'
5. Insert the temp variable defined in step 3.
6. Save and run the bot
7. Change your presence, for example by starting a game.
8. The action will trigger and send out '[object Object]'.

**Expected behavior**
I expect it to store the member object, so it can be used for example, to store the playing status name using that object. Now it is just returning undefined if I try to store anything using the that object.

**Comment by Mindlesscargo** [comment]
That is expected as it's an object.

**Comment by Ryckie** [comment]
The object doens't contain any data.

**Comment by Mindlesscargo** [comment]
Have you confirmed that it is indeed blank? `console.log` it

**Comment by Ryckie** [comment]
https://cdn.discordapp.com/attachments/754216344739643493/756289237875163217/unknown.png
Yes it is empty

**Comment by Thaliruth1** [comment]
I use this presence update myself to promote users in a channel who are streaming on Twitch. The event works for me without any problems, there is [object Object] right again.

Just make Store member info etc. then everything works. At least on my systems and I use Presence Update very often!

**Comment by Ryckie** [comment]
I am not trying to see if they are streaming on Twitch, I am trying to store the name of the game they are playing.
But this keeps returning **undefined** for me.
Using latest mods, node v12.18.4, Discord.js V12.2.0 also bot intents are at all, both in dbm and in developer portal.
Screenshot of my event and actions:
![image](https://user-images.githubusercontent.com/63733138/94158944-46c97480-fe83-11ea-8359-3646acc6f780.png)

Action 3:
![image](https://user-images.githubusercontent.com/63733138/94158909-3b764900-fe83-11ea-982e-851f767f1e29.png)

Console output from that action: 
![image](https://user-images.githubusercontent.com/63733138/94158823-21d50180-fe83-11ea-8c42-089e58c29962.png)

**Comment by Thaliruth1** [comment]
Just use Store Game Info Mod

**Comment by Ryckie** [comment]
> Just use Store Game Info Mod.

Now my console if getting over spammed with this:
```
Error with the command "Store Game Info", Action #3:
TypeError: Cannot read property 'activities' of undefined
```
I don't think there is a way to check if it is defined beforehand.

**Comment by Thaliruth1** [comment]
Sorry, but anyway, it is not a bug. Because the mods work fine. I myself use Game Store Info without any problems. You have to check your raw data and build it correctly! Otherwise, contact the DBM Server and get help from the support!

**Comment by Ryckie** [comment]
What makes you assume it is not a bug?
Not to be rude.. but..
If it returns undefined but it is defined in the object. It is a bug.

**Comment by Thaliruth1** [comment]
It works for me too, if I use the Event Presence Update and I add the Action Store Game Info to get the name of the game, then I get the name of the game. So you have a bug in your structure somewhere. Otherwise I cannot explain it. But only with Presence Update you can't get the game name out of the game, so you have to use Store Game Info. And as I said, it works fine for me, but not for you. So the error is here with you and not with the mod.

**Comment by Ryckie** [comment]
Then the issue if probably with the Store Member Info action and not with the event trigger.
![image](https://user-images.githubusercontent.com/63733138/94181588-fdd3e900-fe9f-11ea-9ca2-54aba7dc956e.png)
Feel free to try and see for yourself it it returns the game or undefined when someone starts a game.
`{
  "name": "presence update",
  "temp": "",
  "event-type": "21",
  "_id": "olljB",
  "actions": [
    {
      "member": "2",
      "varName": "member",
      "info": "0",
      "varName2": "",
      "iftrue": "1",
      "iftrueVal": "",
      "iffalse": "0",
      "iffalseVal": "",
      "name": "Check If Member"
    },
    {
      "member": "2",
      "varName": "member",
      "info": "14",
      "storage": "1",
      "varName2": "playingStatusName",
      "name": "Store Member Info"
    },
    {
      "tosend": "${tempVars(\"playingStatusName\")}",
      "color": "#ffff00",
      "name": "Send Message to Console"
    }
  ],
  "temp2": "member"
}`

**Comment by Thaliruth1** [comment]
Sorry, like I said it works fine for me. I don't have time and I don't want to tell you what you are doing wrong. You should also use Store Game Info in connection with Presence Game. This way you can also check the status of the game.

So now I'm out too, just wanted to say that the event works.

Also the Event Presence Update is not even a MOD of the DBM Network, but a standard DBM Event, so if you have problems with it please contact DBM
