### ISSUE TITLE
Add Member Role action doesn't work when role and servermember are a variable

### ISSUE THREAD

**Issue by TakeOnMii** [dbm-network/mods#581]
You can't give someone a role only using variables. Just when you use for example command author gets the role admin.
![Screenshot_11](https://user-images.githubusercontent.com/62900202/94350483-074f8380-004f-11eb-88f3-fcb3e25bca7f.png)
^❌That doesn't work❌

![Screenshot_12](https://user-images.githubusercontent.com/62900202/94350497-2221f800-004f-11eb-91a2-f8216d207134.png)
^✅That does work✅

**Comment by cadjonathan** [comment]
It should only be User not ${tempVars("User")}

**Comment by Thaliruth1** [comment]
I have tested it

Action 1 Find Role
Action 2 Add Role

Works wonderfully for me. the test user has received his role. Check your console for possible error messages. So there is no bug because it works!

**Comment by TheMonDon** [comment]
I tested this and can confirm that I can not get this to work. Here is my raw data for someone else to try: https://pastebin.com/5drvvsB4

I will send this to DBM creator to let him know of this error.
