### ISSUE TITLE
[Music] I can't use the Search-YouTube-Mod...

### ISSUE THREAD

**Issue by Opofde** [dbm-network/mods#586]
So...
I have the issue, the, whenever I try to use the search_youtube_MOD.json, it says:
`? Error with the command "YouTube Search", Action #10:
? TypeError: this.getMods is not a function
?`
How can I fix this?

~opofde

**Comment by TheMonDon** [comment]
This is not a valid issue with the mod, this is an issue with your Discord Bot Maker not being up to date.
