### ISSUE TITLE
Await Reaction

### ISSUE THREAD

**Issue by Hecticmate** [dbm-network/mods#592]
**Describe the bug**
Command only works if i personally run it first after a bot restart, if another user attempts to run it first it will not work 100%

**To Reproduce**
> I have a command users run which requests information eg. a URL
>  Once they enter the URL the bot awaits response, once response is receive it stores & sends that message to another channel 
> 2 reactions are automatically added also ( Ticket and a X )
> If i click the 'tick' reaction it will send a msg back to the user saying 'approved'
> However this only works if i run the command first, and go through the above stages, If i restart the bot and don't run these commands first myself when someone else tries to do it, it will not work. 

**Expected behavior**
Ability to work without having to personally run the command first.

**Comment by DetroitWhiskey136** [comment]
Can you provide some screen shots of the commands upper properties along with the await reactions properties?

**Comment by DetroitWhiskey136** [comment]
also for better support join the mods support server https://discord.gg/3QxkZPK

**Comment by Hecticmate** [comment]
https://prnt.sc/v7ns4i - Current commands - WIP however.
https://prnt.sc/v7nsgz - Await reactions 

I'm also in the discord, if you would like to see a 'live' demonstration just let me know.

**Comment by marceaupatu123** [comment]
@Hecticmate May i have the raw data ?

**Comment by Kaey87** [comment]
I have the self problem with await reaction. IIi cant use it wiith Init or Call. Her the errormessege from the Bot Log:

`? (node:72464) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'author' of 'message' as it is null.
?     at ReactionCollector.msg.awaitReactions.max.max [as filter] (C:\***\actions\await_reaction_call_action_MOD.js:215:17)
?     at ReactionCollector.handleCollect (C:\***\node_modules\discord.js\src\structures\interfaces\Collector.js:92:53)
?     at Client.emit (events.js:323:22)
?     at MessageReactionAdd.handle (C:\***\node_modules\discord.js\src\client\actions\MessageReactionAdd.js:46:17)
?     at Object.module.exports [as MESSAGE_REACTION_ADD] (C:\***\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_REACTION_ADD.js:4:37)
?     at WebSocketManager.handlePacket (C:\***\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
?     at WebSocketShard.onPacket (C:\***\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
?     at WebSocketShard.onMessage (C:\***\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
?     at WebSocket.onMessage (C:\***\node_modules\ws\lib\event-target.js:125:16)
?     at WebSocket.emit (events.js:311:20)
? (node:72464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
? (node:72464) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
?`

**Comment by almeidx** [comment]
> I have the self problem with await reaction. I cant use it with Init or Call. Her the errormessege from the Bot Log:
> 
> ? (node:72464) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'author' of 'message' as it is null.
> ? at ReactionCollector.msg.awaitReactions.max.max [as filter] (C:***\actions\await_reaction_call_action_MOD.js:215:17) ? at ReactionCollector.handleCollect (C:***\node_modules\discord.js\src\structures\interfaces\Collector.js:92:53)
> ? at Client.emit (events.js:323:22)
> ? at MessageReactionAdd.handle (C:***\node_modules\discord.js\src\client\actions\MessageReactionAdd.js:46:17) ? at Object.module.exports [as MESSAGE_REACTION_ADD] (C:***\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_REACTION_ADD.js:4:37)
> ? at WebSocketManager.handlePacket (C:***\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31) ? at WebSocketShard.onPacket (C:***\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
> ? at WebSocketShard.onMessage (C:***\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10) ? at WebSocket.onMessage (C:***\node_modules\ws\lib\event-target.js:125:16)
> ? at WebSocket.emit (events.js:311:20)
> ? (node:72464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> ? (node:72464) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ?

The message variable you used was null (didn't quite exist)

**Comment by Ferefang** [comment]
/home/niels/Desktop/EeveeBot/actions/await_reaction_call_action_MOD.js:215
        const { author } = message
                ^

TypeError: Cannot destructure property 'author' of 'message' as it is undefined.
    at ReactionCollector.msg.awaitReactions.max.max [as filter] (/home/niels/Desktop/EeveeBot/actions/await_reaction_call_action_MOD.js:215:17)
    at ReactionCollector.handleCollect (/home/niels/Desktop/EeveeBot/node_modules/discord.js/src/structures/interfaces/Collector.js:92:46)
    at Client.emit (node:events:388:22)
    at MessageReactionAdd.handle (/home/niels/Desktop/EeveeBot/node_modules/discord.js/src/client/actions/MessageReactionAdd.js:44:17)
    at Object.module.exports [as MESSAGE_REACTION_ADD] (/home/niels/Desktop/EeveeBot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_REACTION_ADD.js:4:37)
    at WebSocketManager.handlePacket (/home/niels/Desktop/EeveeBot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/home/niels/Desktop/EeveeBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (/home/niels/Desktop/EeveeBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
    at WebSocket.onMessage (/home/niels/Desktop/EeveeBot/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (node:events:376:20)

Got a same problem with it.. i'm using a event to create a channel and after that a msg in that channel.

**Comment by TheMonDon** [comment]
Closing this as this is not an issue with the action, but rather with the message object author being empty, or there being no stored message.
