### ISSUE TITLE
Check Valuable = Valuable MOD

### ISSUE THREAD

**Issue by SolDevelop** [dbm-network/mods#596]
**Is your feature request related to a problem?**
No
**Describe the ideal solution**
<h1> If I had a valuable and I have another valuable I want to check if the first valuable = the next valuable , and that will help as with verify system
And more </h1>

**Describe alternatives you've considered**
None

**Additional context**
`None`

**Comment by RigidStudios** [comment]
what the hell are you on about? just use check variable (equals) lmao

**Comment by DetroitWhiskey136** [comment]
checking if a variable equals another variable is already a feature so i'm closing this issue

**Comment by SolDevelop** [comment]
> checking if a variable equals another variable is already a feature so i'm closing this issue

How to do it
