### ISSUE TITLE
Action "Check Variable" problem

### ISSUE THREAD

**Issue by NGTV1234** [dbm-network/mods#603]
The Check Variable action is broken, it won't work no matter what I do. Latest version of the action is bugged (I use latest version)
(I used normal strings, normal numbers. I tried using different variations. I tried using regex to hopefully check it, but it did not work.)

**Comment by Lucasamiel0406** [comment]
Screenshot of your action, the Check Variable and what you're trying to check

**Comment by NGTV1234** [comment]
![image](https://user-images.githubusercontent.com/36736534/100051464-f69a6e80-2e41-11eb-9fac-6cc96c77d563.png)

I'm trying to check for s/m/h/d (seconds, minutes, hours days) for a giveaway bot creation.
