### ISSUE TITLE
Problem with "Youtube Search" Mod, any fixes?

### ISSUE THREAD

**Issue by PGamingHD** [dbm-network/mods#609]
**Describe the bug**

I cannot search for a youtube video without getting a strange error, placed the API key in the right place and everything but still won't work.

**Expected behavior**

Wanted it to search for a vid on youtube with a string then take the first vid it found then start playing it. However doesn't do that just gives some kinda error at the search for youtube vid part.

**Screenshots**

https://gyazo.com/560d4ac619c531bf057ac0af02e8c7ce

**Comment by Zylops** [comment]
same here, please lmk if you found any fixes :)

**Comment by master3395** [comment]
Try this
https://github.com/dbm-network/mods/pull/587

**Comment by tsargoth** [comment]
I'm also experiencing the issue with YouTube search. APIkey is restricted to YouTube data V3 and the YouTube v3 api is enabled. Billing is also linked. Google console shows that something is hitting the API with an error
