### ISSUE TITLE
Member waiting mod

### ISSUE THREAD

**Issue by SolDevelop** [dbm-network/mods#611]
**Is your feature request related to a problem? Please describe.**
No
**Describe the ideal solution**
I want to put a timer in command for when the member use this command he need to wait a time and the maker can set the time like put the time here then choose hours or days or minutes or secs or weeks
**Describe alternatives you've considered**
Like this
Put the time that’s member need to wait to use this command again
**Additional context**
I can’t

**Comment by TheMonDon** [comment]
This is already possible in default DBM, just right click on a command.
