### ISSUE TITLE
Support "Jump To Anchor" in "Check Variable Type"

### ISSUE THREAD

**Issue by Michael55555** [dbm-network/mods#613]
**Is your feature request related to a problem? Please describe.**
If you use "Check Variable Type" you cannot jump to an anchor after checking the type. 

**Describe the ideal solution**
An option to choose "Jump to Next Anchor" if the result is true or false.

**Describe alternatives you've considered**
I have considered using a script for this, but it should be definitely easier to do, especially for our fellow non-developers.

**Additional context**
What it looks like at the moment:
![image](https://user-images.githubusercontent.com/30301026/101993853-062d0a80-3cbe-11eb-9cae-64a8e40f9d50.png)
What it should look like:
![image](https://user-images.githubusercontent.com/30301026/101993881-34124f00-3cbe-11eb-9735-7c032d6272e3.png)

**Comment by marceaupatu123** [comment]
Check Variable Type isn't from mod :/

**Comment by Michael55555** [comment]
> Check Variable Type isn't from mod :/

Yes, I am aware of that. But it can easily be modded. We have the files in the command's folder. 😃
So this would be the tasks for this issue:

- [ ]  Put a copy of "commands/check_variable_type.js" from a regular DBM folder into the "mods/commands/" folder
- [ ]  Edit functions to fix the issue
- [ ]  Convert object into class
- [ ]  Lint and push changes

Hope this helps! 🙌🏻
