### ISSUE TITLE
Check if delivery fails on send message action does not work, it does not get triggerd -no errors

### ISSUE THREAD

**Issue by martinbndr** [dbm-network/mods#629]
**Describe the bug**
The Check if delivery fails on the send message action does not work. It won't get triggered. Would be cool if this can be fixed.

**To Reproduce**
1. Create command/event'
2. build a command/event that sends a message  '....'
3. build diffrent actions in this command / event and the bot needs to send a message  '....'
4. Create some actions that will triggerd if the message failed to send and set the action to jump to it on the send message action
5. Run the command/event, test it out by removing the bot perms to channel where the bot need to send it by the channel id
(of course find channel is in your event/command)
6. or delete the channel and try let the bot send the message

There is no error printing into the console

**Expected behavior**
The bot should jump to the action(s) and execute them but nothing happens, no errors nothing.

**Comment by TheMonDon** [comment]
It seems this might be expected behavior, but not sure, but what you describe is correct.
