### ISSUE TITLE
Working Music System & Lavalink System

### ISSUE THREAD

**Issue by erturkdotgg** [dbm-network/mods#631]
We need a really stable music system for DBM, FFmpeg and ytdl-core is not working properly for some of the bots. Please make a mod for Lavalink like(Connect to lavalink) (Play from lavalink and etc)

Its just a request but everyone really needs that than other mods.

**Comment by TheMonDon** [comment]
I don't think this is a good idea because most people do not want to use an external server for music, and for the most part, ytdl-core and FFmpeg work fine.

**Comment by erturkdotgg** [comment]
> 
> 
> I don't think this is a good idea because most people do not want to use an external server for music, and for the most part, ytdl-core and FFmpeg work fine.

Its not working fine sir, when you look to support channels at DBM Discord, many people know that the music system is not stable in DBM. For Lavalink, suggestions were given on the "mod-suggestions" channel several times but nobody did. Discord Bot Maker community really needs that mods.

**Comment by Lucasamiel0406** [comment]
> [...] Discord Bot Maker community really needs that mods.

Generally people complains about Youtube Search, that's the main issue 85% of the time. I already helped more than just 10 members in the server and all the issues was about search, people don't know and ask about it, not "music isn't stable".

**Comment by TheMonDon** [comment]
Closing this as YouTube is fine, and lavalink system is too complicated for DBM users.
