### ISSUE TITLE
DBM Sharding

### ISSUE THREAD

**Issue by master3395** [dbm-network/mods#633]
I've been looking at the old custom files for sharding, and I can't see much documentation.
But I've seen DBM bots that have grown a lot lately.
And I was thinking perhaps it should be an alternative if it does not get implemented into DBM itself?

Posting a link below to my old issue on the old custom files.
https://github.com/dbm-network/custom-files/issues/4

**Comment by DomeQdev** [comment]
https://anidiots.guide/understanding/sharding 

dbm is shit, don't use it

**Comment by Zerlingg** [comment]
I agree, this could be useful as hell, i have found a lot of problems with sharding. Have tried some stuff myself but didnt go well

**Comment by DomeQdev** [comment]
It's why you need to start learning normal js, dbm is big shit

**Comment by Zerlingg** [comment]
> It's why you need to start learning normal js, dbm is big shit

i mean, i get your point, but what about those who do not want, do not have the time or the bot is already too big (the ammount of things it has) for just re-making it all in js?

**Comment by master3395** [comment]
> It's why you need to start learning normal js, dbm is big shit

Your reply does not really help in any way.
It does not solve my issue and rather insulting replies.

I use DBM, and I'd rather use DBM than use JS by default.
It's time-consuming to use DBM than to use plain JS.

Yes, I do know how to use JS, but no I do not know how to use sharding with DBM.
And that is why the suggestion is here.

**Comment by TheMonDon** [comment]
Forgot this was an issue but there is now a new bot-sharder that works in this repo.
