### ISSUE TITLE
Run SQL Query flood console

### ISSUE THREAD

**Issue by Giingu** [dbm-network/mods#635]
**Describe the bug**
When using SQL Query mod it sends to console the actions every single time it is used even when debug is off.

> This is specially anoying when you have leveling systems based on user activity.

**To Reproduce**
Simply use the mod and check the console, you will see that even if debug is off it spits out stuff into the console

**Expected behavior**
No messages on console if debug mode is off
It would be nice if we could have an option to disable the message telling us what it does every single time and instead only tell us when it isnt able to reach the database, has any errors, etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/38077912/106382382-89fe9b80-63bf-11eb-8351-0cb3bc596d7d.png)

**Comment by DetroitWhiskey136** [comment]
#848
