### ISSUE TITLE
Bot watching Youtube Channels

### ISSUE THREAD

**Issue by frostfire1** [dbm-network/mods#637]
I tried to put Youtube channel url in the activity watching bot and it doesn't work

**Comment by Lucasamiel0406** [comment]
![image](https://user-images.githubusercontent.com/49658726/107171544-d2125500-69a1-11eb-97b7-f8b38fa626f4.png)

If you're using Streaming, Discord API doesn't allow other URLs than Twitch URLs.

**Comment by frostfire1** [comment]
okay tnks
