### ISSUE TITLE
Play_youtube.js is broken with error: Error: Error parsing info: Unexpected token ) in JSON at position 0  

### ISSUE THREAD

**Issue by SiSchu** [dbm-network/mods#639]
The play_youtube.js is broken and doesn't work...please fix that!

**Comment by Lucasamiel0406** [comment]
Just saying that something is broken don't help devs or anyone to help you.
"911 what's your emergency"
"He's dying"
"Who?"
"*He's dying!"

Explain what is actually happening and how to reproduce it.

**Comment by TheMonDon** [comment]
This can be fixed by updating ytdl-core `npm i ytdl-core@latest`
