### ISSUE TITLE
Play_youtube.js is broken

### ISSUE THREAD

**Issue by SiSchu** [dbm-network/mods#640]
with error: Error: Error parsing info: Unexpected token ) in JSON at position 0
 I reinstalled it several times but it won't play anything

![image](https://user-images.githubusercontent.com/49567870/107672686-7abbff80-6c95-11eb-839c-e3c1dc50e864.png)

**Comment by Lucasamiel0406** [comment]
There was no need to create a whole different issue and leave your first there. #639
