### ISSUE TITLE
Slash Commands

### ISSUE THREAD

**Issue by MicroGitHubFox** [dbm-network/mods#650]
**Is your feature request related to a problem? Please describe.**
Not an issue.

**Describe the ideal solution**
No solution

**Describe alternatives you've considered**
Nope

**Additional context**
Add Slash Commands as a mod to DBM

**Comment by Lucasamiel0406** [comment]
No

**Comment by callmehSpear** [comment]
yeah... no...

**Comment by ryjayt** [comment]
I think a **slash command** mod would be **amazing**.

**Comment by Lucasamiel0406** [comment]
> I think a **slash command** mod would be **amazing**.

Yeah, would be cool, *but it's not even added to Discord.JS*.

**Comment by TheMonDon** [comment]
This is on hold until discord.js implements slash commands feature that we're able to work with easily.

**Comment by MrNoverGitHub** [comment]
I shall await the day Slash Commands will be available with DBM. 🔥

**Comment by almeidx** [comment]
Slash Commands will be built into DBM itself.
