### ISSUE TITLE
MSSQL Connection Problem

### ISSUE THREAD

**Issue by LukasCCB** [dbm-network/mods#651]
**Describe the bug**
When I log in to MSSQL on other systems, it works. but when I use DBM to connect MSSQL, it gives an error. However when I check it works.

Return erros: `DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066`

I have last MODS installed. Last version DBM (no Betas selected), last Node installed on this Data of post.

**Screenshots**
![image](https://user-images.githubusercontent.com/6683056/109367742-b2ba6980-7875-11eb-92e9-7120060cde4a.png)
![image](https://user-images.githubusercontent.com/6683056/109367748-b51cc380-7875-11eb-9b2a-e0492a581326.png)

**Comment by TheMonDon** [comment]
This is an issue with your server not the mod.

**Comment by LukasCCB** [comment]
> This is an issue with your server not the mod.

No. When I use other method for connection. work.

**Comment by TheMonDon** [comment]
> > This is an issue with your server not the mod.
> 
> No. When I use other method for connection. work.

Okay, I understand now. Still not an issue with the actual mod but seems to be something with how you connect to the server, I found this github issue on the module this uses:

https://github.com/tediousjs/node-mssql/issues/884

Going to reopen for now and look into this a bit I guess

**Comment by LukasCCB** [comment]
@TheMonDon yes, I have search many results about this problem Tedious with MSSQL. If usage other port, not default 1433. give problem also. and if disabled 2 option in config for ignore security connection. something this.

I'm now using PHP API (JSON method) for call with my database. sending URL _GET with ID and user informations.

**Comment by OneAndonlyFinbar** [comment]
Pretty sure this is an issue either with the configuration of your server or how you're using the action, rather than an inherent flaw in the action itself.
