### ISSUE TITLE
Add Item/Get Item/ Remove Item from list "set position value" doesn't work

### ISSUE THREAD

**Issue by KaiaraChan** [dbm-network/mods#659]
putting a variable in the position slot for "Get Item From List" and "Remove Item From List" stops the chain of actions and gives you this error: Error with Event "Remove Item from List", Action #22: TypeError: Cannot read property 'temp' of undefined, this happens with any of the Add Item/Get Item/Remove Item from list actions,  I looked up this error on the discord and its been going on since 02/27/2018 and no one has done anything

**To Reproduce**
1. Go to 'A command'
2. Click on 'Actions'
3. Scroll down to 'Add item to list'
4. Put a variable in the set position value
5. Run Command
6. see an error

**Expected behavior**
I Expect the bot the bot to add an item to the list at my desired position, the position being a temp variable. 

**Screenshots**
![image](https://user-images.githubusercontent.com/83102954/115943829-2e085800-a480-11eb-85b5-f8b94260b165.png)
![image](https://user-images.githubusercontent.com/83102954/115943835-36f92980-a480-11eb-9ba8-0d4692c2f09b.png)
![image](https://user-images.githubusercontent.com/83102954/115943844-40829180-a480-11eb-9f73-d2170e691bc7.png)

**Comment by RediPanda** [comment]
Hi @KaiaraChan,

I was able to reproduce your bug and I was able to push out a PR (#660) to remedy this issue.

**Comment by TheMonDon** [comment]
Closed as it was fixed with #660
