### ISSUE TITLE
Find Item In List Bug

### ISSUE THREAD

**Issue by DorimeDoge** [dbm-network/mods#663]
Hello,

Find Item In List doesn't work with list that is saved in global vars. It just says underfined.
![image](https://user-images.githubusercontent.com/57041295/117409763-3c438300-af1a-11eb-8df7-dc3b9fa9472f.png)

**Comment by TheMonDon** [comment]
The action works fine for me, with global variable. Make sure you're using Save Variable action to save the global variable.
