### ISSUE TITLE
Sorting not working

### ISSUE THREAD

**Issue by cookieXL** [dbm-network/mods#693]
**Describe the bug**
Whenever you use the "Sorting" option for the Member Data List action or any other List action, it simply just does **not** sort. And yes, I have ran ``npm i jsonpath-plus`` and ``npm i fast-sort``

**To Reproduce**
1. Make a command that creates some kind of list of a variable using the member data list action, make sure to have multiple people added to this list.
2. Run the command 
3. See that it does not sort properly

**Expected behavior**
Should be sorting lists.

**Screenshots**
![image](https://user-images.githubusercontent.com/62772011/121968344-718d8d00-cd72-11eb-84de-8fd854dcdedc.png)

**Comment by TheMonDon** [comment]
Fixed in #696
