### ISSUE TITLE
Top.gg API extension

### ISSUE THREAD

**Issue by master3395** [dbm-network/mods#707]
Hello.

When i tried the Top.gg API extension, my bot returns this error every restart of the bot.
Not sure if it's an issue on my end, or if there's an issue in the code.

![image](https://user-images.githubusercontent.com/4199669/122831905-da34b680-d2ea-11eb-9f53-717dbeb0c90f.png)

**Comment by shinobihaxor** [comment]
Works fine for me, just tested, please check if your token is correct and port is listened on 5000

**Comment by master3395** [comment]
Just tried, and it still does not send the information to top.gg

It says Server Count 131 on top.gg
While it really is Server Count 129.

I got  Node v12.22.2

**Comment by master3395** [comment]
Works now.
