### ISSUE TITLE
Multiple Embeds support

### ISSUE THREAD

**Issue by tlfn** [dbm-network/mods#717]
**Is your feature request related to a problem? Please describe.**
Nah

**Describe the ideal solution**
Edit some related actions? 

**Describe alternatives you've considered**
idk

**Additional context**
Normal bots are able to send multiple embeds in normal message due to recent change from Discord; DBM mods don't seem to support this

**Comment by Lucasamiel0406** [comment]
The main question is: Is it on DJS or what?

**Comment by tlfn** [comment]
You can at least store whole embeds array in some actions for now, not first embed. And I don't know

**Comment by almeidx** [comment]
It's available on the dev version, not stable
