### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by sajjadRetro** [dbm-network/mods#728]
I think i found some bugs

1: you only can edit those embeds that you created in command. there is no action to find an embed message or edit it.
2: i cant make embeds in the events section like when i create embed and i want to add field on it i cant find my embed on temp vars. i tried it by just typing the name of var but it didn't work.
3: in "await response" action when i store the response in a data it works until bot restarts. after restart the data turns into a text like [object:object].
4: there is no jump to anchor in "check variable type" action.

**Comment by tlfn** [comment]
1, 4 are not a bug

**Comment by sajjadRetro** [comment]
> 1, 3, 4 are not a bug
> And please create a separated issue per issue

these features will be added?

**Comment by DetroitWhiskey136** [comment]
embed messages aren't a thing
what you call an embed message is just a normal message with an embed object added to it so you can use the find message action to find the message because its a message... logic 101
