### ISSUE TITLE
Dashboard issue

### ISSUE THREAD

**Issue by master3395** [dbm-network/mods#739]
1. Dashboard is made for localhost not using HTTPS (Issue for websites running Linux with the dashboard using HTTPS)
2. Clicking one of the servers takes you to the URL below
http://IP:3000/dashboard/@me/servers/example numbers for 1 server here.
Shows this issue below.
PS: I know the dashboard isn't 100% working, just pointing out an issue.
![image](https://user-images.githubusercontent.com/4199669/125205314-eaa0d700-e281-11eb-8204-dd2d0b3f0d4d.png)

**Comment by Mindlesscargo** [comment]
Are you saying that you cannot use https on your dashboard?

**Comment by master3395** [comment]
Correct, i can use it on HTTP, but HTTPS results in an internal 500 error on some things.
But part 2 has nothing to do with HTTPS, it stops on HTTP also.

You can see on my URL below, I had to turn off CloudFlare.
It messed with things.
But I'm using let's encrypt for the SSL here.

https://dashboard.newstargeted.com/

![image](https://user-images.githubusercontent.com/4199669/125212282-94955900-e2ac-11eb-812c-509007a42dd1.png)

**Comment by master3395** [comment]
> Are you saying that you cannot use https on your dashboard?

Correct, i can use it on HTTP, but HTTPS results in an internal 500 error on some things.
But part 2 has nothing to do with HTTPS, it stops on HTTP also.

You can see on my URL below, I had to turn off CloudFlare.
It messed with things.
But I'm using let's encrypt for the SSL here.

https://dashboard.newstargeted.com/

![image](https://user-images.githubusercontent.com/4199669/125212282-94955900-e2ac-11eb-812c-509007a42dd1.png)

**Comment by master3395** [comment]
> Are you saying that you cannot use https on your dashboard?

Correct, i can use it on HTTP, but HTTPS results in an internal 500 error on some things.
But part 2 has nothing to do with HTTPS, it stops on HTTP also.

You can see on my URL below, I had to turn off CloudFlare.
It messed with things.
But I'm using let's encrypt for the SSL here.

I see that I'm having issues with the authentication.
Because the URL to the authenticator is not really an URL.
The bot is using a proxy using OpenLiteSpeed to convert the site to show.
But I'm not sure how to get the authenticator to show.
Because that is located in a different folder than where the bot is.

Where bot is located: /home/dashboard.newstargeted.com/public_html/nt/extensions/dashboard_EXT

Where the oauth module is:
/home/dashboard.newstargeted.com/public_html/nt/extensions/aaa_extensionHelper_EXT/dashboard_EXT/node_modules/oauth

https://dashboard.newstargeted.com/

![image](https://user-images.githubusercontent.com/4199669/125212282-94955900-e2ac-11eb-812c-509007a42dd1.png)

**Comment by DetroitWhiskey136** [comment]
The dashboard is something that will probably be removed as non of the mod devs want to maintain it. Its more of a hassle than its worth

**Comment by DetroitWhiskey136** [comment]
#848
