### ISSUE TITLE
Find Member errors out instead of passing

### ISSUE THREAD

**Issue by dashZdash** [dbm-network/mods#748]
**Describe the bug**
"Find Member" for the most part does what its intended, but the part "If member wasn't found" does not function. When using the action, when the member cannot be found instead of passing to the fail part it just errors out and does nothing.

**To Reproduce**
1. Create a simple find member command
2. set the "If member wasn't found" to have a function
3. Provide the command a valid and non-valid member ID
4. Look at the console and view the error that is presented when the invalid ID was presented

**Expected behavior**
When provided with an invalid member ID, the action is supposed to initiate the "If member wasn't found", but instead it errors out.

**Screenshots**
![image](https://user-images.githubusercontent.com/34530883/126381279-3e286f37-e6e7-4028-87a6-0dbfb860d51b.png)
![Screenshot 2021-07-20 150803](https://user-images.githubusercontent.com/34530883/126381547-41fabeec-05ca-4577-a764-ed5b5377cd30.png)

**Comment by shinobihaxor** [comment]
I'm positive that this happens only when your bot does not have intents enabled, please check if your bot has all intents enabled.

**Comment by dashZdash** [comment]
> I'm positive that this happens only when your bot does not have intents enabled, please check if your bot has all intents enabled.

I have intents fully enabled, and I'm not sure why it would be the issues here, the actions can find ID's I need it to do what its supposed to when it can't find the ID, it wouldn't need intents for intentional failing.

**Comment by TheMonDon** [comment]
99% this is an intents bug that is probably solved by now.
