### ISSUE TITLE
canvas.node is not a valid win32 application.

### ISSUE THREAD

**Issue by IMikoKoneko** [dbm-network/mods#766]
**Describe the bug**
Canvas edit plugins are sending this error.
"canvas.node is not a valid win32 application."

**To Reproduce**
1. Create new command
2. Add example "Canvas Edit Image Border"
3. Run command

**Expected behavior**
Draw bordered avatar image on image

**Screenshots**
No screenshots, not at home.

**Comment by Mikee90165** [comment]
_That's not a bug, run your bot thorugh command prompt._

**Comment by IMikoKoneko** [comment]
> _That's not a bug, run your bot thorugh command prompt._

It is. I tried same via cmd

**Comment by Mikee90165** [comment]
_Did you even bother to ask in the support channels in the Discord server  instead of opening a  discussion here? Type the error in the search bar in **DBM Mods** server and you'll see the answer is the same as the one I told you._

**Comment by IMikoKoneko** [comment]
> _Did you even bother to ask in the support channels in the Discord server instead of opening a discussion here? Type the error in the search bar in **DBM Mods** server and you'll see the answer is the same as the one I told you._

I'm banned -_-

**Comment by Mikee90165** [comment]
_Well, that's not my problem. You can request a ban appeal using the support site._
https://dbm-support.site
