### ISSUE TITLE
Issue with Store JSON From Web API | Does not store all JSON paths if left blank

### ISSUE THREAD

**Issue by WolfoTheWolf** [dbm-network/mods#768]
**Describe the bug**
Store JSON from web API, When I leave the path blank (to store everything) it will return as ""object Object" but will paste the JSON in the console if debug mode is on. (have made sure it wasnt the api)

**To Reproduce**
1. Go to Your project and make a new command, add a "Store JSON From Web API" 
2. Input "https://dog.ceo/api/breeds/image/random"
3. turn debug on
3. Leave the Path blank (to store everything)
4. Store in temp var
5. send message with that temp var
6. will return object
7. check console has the data listed there 

**Expected behavior**
It will return object in a message and in the console paste it properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/56661068/131027134-47c3cfda-9a6f-41f3-8b98-31307aba7cc2.png)
![image](https://user-images.githubusercontent.com/56661068/131027156-0a5e850a-e3de-471a-afe7-fa850956cf44.png)
![image](https://user-images.githubusercontent.com/56661068/131027179-2b8b8f3b-0a8d-4a2a-8841-4286013d0648.png)
![image](https://user-images.githubusercontent.com/56661068/131027224-f0efa75f-8a5f-403a-a932-cc8a0c8a0a8c.png)

**Comment by OneAndonlyFinbar** [comment]
Can be fixed with parse from stored json mod, or by utilizing the stringify output option.
