### ISSUE TITLE
Global varible not working.

### ISSUE THREAD

**Issue by WolfoTheWolf** [dbm-network/mods#773]
**Describe the bug**
On the action `find webhook` if you set it to global then try to use the webhook from the global var it will not work.

**To Reproduce**
1. Make a event on bot start
2. Click on find webhook then store the data in a global variable 
3. Call the variable from another command

**Expected behavior**
You will get a error in the console 

**Screenshots**
![image](https://user-images.githubusercontent.com/56661068/133504306-1bc55d7e-891f-44fe-b1a4-3f7130814ee4.png)
![image](https://user-images.githubusercontent.com/56661068/133504324-b5ff544f-cd6b-45cd-9b5e-a62c87584e5b.png)
![image](https://user-images.githubusercontent.com/56661068/133504345-77f940a6-4853-4e58-afbf-5fb519e26af6.png)

**Comment by Lucasamiel0406** [comment]
![image](https://user-images.githubusercontent.com/49658726/133507047-a597e4ff-2204-4515-bdcc-73ba39ffd7bd.png)

Jokes aside, have you tried to find that Webhook using the `Bot Initialization` event and then using `Save Variable` to store it? Also, remember `Find Webhook` just as normal JS promises need a time to be actually found and return the actual result, I suggest adding a `Wait` action before it.
