### ISSUE TITLE
msg author tag id

### ISSUE THREAD

**Issue by master3395** [dbm-network/mods#782]
Not sure if this bug belongs here, or with DBM itself somewhere.
You can't use any of these two tags.
If you remove both, your command will work again.

DBM 2.0

${msg.author.tag}
ID ${msg.author.id}

**Comment by master3395** [comment]
TypeError: Cannot read properties of null (reading 'author')

**Comment by RediPanda** [comment]
It seems the msg object isn't available. (I'll have a chat with SRD/Alm if this was intentional or not)

You can access it directly via `cache.msg` instead.

**Comment by master3395** [comment]
Now I'm confused.
I tried with cache.msg.author.tag but it still reflects the same error.

**Comment by RediPanda** [comment]
Is this in a slash command by any chance?

**Comment by master3395** [comment]
Oh, I thought slash commands could use .msg hm.
