### ISSUE TITLE
Delete bulk messages not working

### ISSUE THREAD

**Issue by Noxxe-0001** [dbm-network/mods#785]
**Describe the bug**
The "Delete Bulk Messages" action is not working when you use them in slash commands. When you use the action, it says that It completed successfully but it hasn't actually deleted any of the messages.

**To Reproduce**
1. Go to 'New action'
2. Click on 'Choose the Delete Bulk Messages action and set it up correctly.'
3. Use the slash command in any discord chat.

**Expected behavior**
Supposed to delete the requested amount of messages.

**Screenshots**
Not Applicable.

**Comment by MazeRunner800** [comment]
I can confirm that I am getting this issue too. https://discord.com/channels/374961173524643843/898376480587907153/899323787823181874

**Comment by DetroitWhiskey136** [comment]
this action will be removed from the mod list in the next update.
