### ISSUE TITLE
Await Response won't continue the actions.

### ISSUE THREAD

**Issue by MichaelColder31** [dbm-network/mods#786]
**Describe the bug**
Await Response won't continue actions. This can be done with **send message** or anything else that requires the bot to do something when Await Response is needed. 

**To Reproduce**
Simple Method.
1. Create a new command.
2. Create a action "Send Message" saying anything e.g "Post Something."
3. Create a action "Await Response" with the settings shown in the image attached.
4. Create a action "Send Message" saying anything.

**Expected behavior**
The Last Action (Send Message) should print out a message but is not.

**Screenshots**
![DBM bug 2](https://user-images.githubusercontent.com/58403578/137692122-2e85fa2e-e9d0-408e-ad47-202fd1a75fb6.png)
![DBM bug](https://user-images.githubusercontent.com/58403578/137692125-c7d77572-751d-4a76-a34e-6f4794c55e67.png)
![Screenshot (307)](https://user-images.githubusercontent.com/58403578/137692177-6cfa7f90-b228-4c45-9386-a25e9ebc0b25.png)

**Comment by MichaelColder31** [comment]
DBM BETA v.2.0.3 Forgot to mention.

**Comment by TheMonDon** [comment]
This should be fixed by now with the latest changes, please make a new issue if any more problems arise.
