### ISSUE TITLE
Play Youtube Action is not working

### ISSUE THREAD

**Issue by erturkgg** [dbm-network/mods#788]
Play Youtube.js is not working on latest DBM Beta Version. When I delete the "aaa_dbmmods_dependencies_MOD" file, the action works, but it is not stable and plays the song directly instead of adding the song to the queue(add to queue selected). Please fix the youtube & music actions. Thanks.

**Comment by DetroitWhiskey136** [comment]
this action will be removed from the mod list in the next update.
