### ISSUE TITLE
How to make mod?

### ISSUE THREAD

**Issue by misha535** [dbm-network/mods#800]
Please, help, i want to make a mod.

**Comment by Dosojin1** [comment]
First of all, this is not a issue ...
Second go to the discord server and ask your question there, not here.
Use github only if you have a real issue with a bot, not if you want to make one

**Comment by misha535** [comment]
Discord server invite a not work

**Comment by Dosojin1** [comment]
dude go to discord for help! I not helping here!^

THIS IS ONLY MOD ISSUES!

**Comment by Lucasamiel0406** [comment]
![image](https://user-images.githubusercontent.com/49658726/143056534-e61d48b0-0baf-4396-a422-afb61545f0eb.png)

**Comment by ThatSmilingTophat** [comment]
skill issue if you ask me
