### ISSUE TITLE
Await response STILL broken.

### ISSUE THREAD

**Issue by MegamiShin** [dbm-network/mods#801]
**Describe the bug**
Await response mod still broken, using the latest one as of now. Doesn't continue actions I presume, no errors whatsoever.

**To Reproduce**
1) Get the latest Await Response mod
2) Try to use it.

**Expected behavior**
Await response continues actions

**Screenshots**
<img width="433" alt="image" src="https://user-images.githubusercontent.com/82964945/143117833-09bed51e-b8fc-4d60-9c99-fbcf81f80d84.png">

**Comment by TheMonDon** [comment]
This should be fixed by now with the latest changes, please make a new issue if any more problems arise.
