### ISSUE TITLE
Issue with "Send message to Console"

### ISSUE THREAD

**Issue by DocTeck** [dbm-network/mods#802]
**Describe the bug**
When i use this action i get an error saying chalk is required, when i type npm i chalk and i retry i got the same error 

**To Reproduce**
1. Go to 'event'
2. Click on 'Send message to Console'
3. Start the event with the bot initialisation

**Expected behavior**
The bot saying a custom message when ready and some logs going into the console when user use a command or something else

**Comment by ForceBlood** [comment]
Are you still experiencing this issue with the latest mods? I just tested and after doing `npm i chalk`, it worked perfectly fine. 
![image](https://user-images.githubusercontent.com/33997884/184556575-e52acc94-7239-4189-aae1-4d290a8fbd64.png)
