### ISSUE TITLE
Issue with Banning by ID

### ISSUE THREAD

**Issue by DocTeck** [dbm-network/mods#803]
**Describe the bug**
I made a command that require the user to give a Discord UID and a reason to ban a member (even if the target isen't in the server) 3 day's ago when i tested it worked, today it's not, i have no error, no message, everything works as expected but the user is not banned from the server

**To Reproduce**
1. Make a command that require a User ID
2. use the "Ban member" with temp vars (or slash var) as target (also works with find user by id) 
3. Try ban a member via his Discord UID

**Comment by DetroitWhiskey136** [comment]
this action will be removed from the mod list in the next update.
