### ISSUE TITLE
[DBM v2] Set Role Permissions

### ISSUE THREAD

**Issue by Ibotmealot** [dbm-network/mods#806]
**Describe the bug**
Using the set role permissions action with v2 doesn't seem to work anymore. 

**To Reproduce**
1. Go to 'Set Role Permissions'
2. Use the action in any way, it seems like it's outdated and still uses bit flags. Therefore, you get this error: **Cannot mix BigInt and other types, use explicit conversions**

**Expected behavior**
The bot edits the roles permissions and doesn't give an error. 

**Screenshots**
![image](https://user-images.githubusercontent.com/42391199/145501498-fe6f16e0-2757-4038-a7a1-511495bd10b6.png)

**Comment by EliteArtz** [comment]
Fixed with Pull Request #859, awaiting approval to the final dbm-mods and then it's good to go.
