### ISSUE TITLE
[DBM v2.x] Store Reaction Info

### ISSUE THREAD

**Issue by master3395** [dbm-network/mods#807]
This command is a Slash command.
![image](https://user-images.githubusercontent.com/4199669/145695567-08a399a7-db9e-433e-b499-bbc1f3c7899f.png)

**Describe the bug**
This Action does not output anything in discord unless it's in an error log.

**To Reproduce**
1. Add Send Message
2. Store Send Message / Data variable
3. Add Add Reaction action
3. Add action Store Reaction Info action
2. Add new Send Message with temp result from Store Reaction Info action.

**Expected behavior**
Stores the reactions from an emoji, then outputs a randomly selected user.

**Screenshots**
![image](https://user-images.githubusercontent.com/4199669/145695465-531a1fab-a176-4265-8f43-12221c23d8ca.png)
![image](https://user-images.githubusercontent.com/4199669/145695475-bf8a0d60-d85c-452a-a01a-b263980e8d8e.png)

**Comment by TheMonDon** [comment]
Closing as I believe this should be fixed by now with different additions to the file.
