### ISSUE TITLE
I can't start my bot when i installed mods

### ISSUE THREAD

**Issue by TypicalShavonne** [dbm-network/mods#812]
**Describe the bug**
I cant start my bot

**To Reproduce**
1. Install DBM fresh from steam
2. Create project
3. Install mods
4. Start the bot

**Expected behavior**
Bot should start normally

Log:
`? C:\Users\tranh\Desktop\S
? impCorev2\actions\check_if_member_has_role_MOD.js:130
?      return mem?.roles?.cache.has(role.id);
?      ^
?
? SyntaxError: Unexpected token '.'
?     at wrapSafe (internal/modules/cjs/loader.js:1072:16)
?     at Module._compile (internal/modules/cjs/loader.js:1122:27)
?     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
?     at Module.load (internal/modules/cjs/loader.js:1002:32)
?     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
?     at Module.require (internal/modules/cjs/loader.js:1044:19)
?     at require (internal/modules/cjs/helpers.js:77:18)
?     at Object. (C:\Users\tranh\Desktop\SimpCorev2\bot.js:362:20)
?     at Array.forEach ()
?     at Object. (C:\Users\tranh\Desktop\SimpCorev2\bot.js:360:23)
?`

**Comment by MaryKirschner** [comment]
are you using the beta?

**Comment by Noxxe-0001** [comment]
It looks like there is something wrong with the "check_if_member_has_role_MOD.js" action, this is what could be causing your bot to stop, try to remove that action from your action sequence and see if that works.

**Comment by TypicalShavonne** [comment]
> 
 i dont have it in my action sequence

**Comment by TypicalShavonne** [comment]
i updated to beta, and it fixed, thanks

Vào Th 5, 16 thg 12, 2021 vào lúc 19:39 Mary ***@***.***>
đã viết:
