### ISSUE TITLE
On bot error catch invite link

### ISSUE THREAD

**Issue by MikuunyA** [dbm-network/mods#813]
**Describe the bug**
For an unknow reason, on bot error event store the invite link when created into the dbm error var

**To Reproduce**
1. Event
2. select "on bot error"
3. store the discord bot maker error inside a var
4. print the var in a message
5. when creating an invite link on a server, the bot send the error message with the link in the dbm error var and undefined for json error

**Screenshots**
https://imgur.com/hTNz5Q8

**Comment by ParallaxOnline** [comment]
Can confirm this does happen.

**Comment by DetroitWhiskey136** [comment]
forwarded to srd

**Comment by almeidx** [comment]
Fixed in 2.1.7
