### ISSUE TITLE
Check Member Permission - Outputting wrong [V2.x]

### ISSUE THREAD

**Issue by master3395** [dbm-network/mods#820]
**Describe the bug**
`Check Member Permission` when it tries to check if the interacted user has permission, I am the owner, so it should allow me to continue.

**To Reproduce**
1. Add send button.
2. Add button.
3. Edit Button.
4. Add Check Member Permission action.
5. If true continue, if false jump and send a new message.

**Expected behavior**
It would find me as the owner that has the permission and continue to send the message.

**Screenshots**
![image](https://user-images.githubusercontent.com/4199669/146621312-f752c3f9-f594-41c7-adb6-013de9ebce7d.png)

**Comment by DetroitWhiskey136** [comment]
not a mod
