### ISSUE TITLE
Issue with a say command.

### ISSUE THREAD

**Issue by darkspyro92** [dbm-network/mods#821]
**Describe the bug**
Whenever I use my Say command with my bot, it sends this error. It worked perfectly fine for months until recently. I did update my mods, so not sure if that had anything to do with it.

**To Reproduce**
1. !say #channel-name
2. Get prompted to enter text to send.
3. Enter text to be sent.
4. Error gets thrown.

**Expected behavior**
The text should be sent to the channel that is specified in the command. The problem occurs when it gets to Await Response and I enter the text. It doesn't seem to store the text and continue to the next actions. I've tried a few different methods and workarounds with all failed results. I'm not sure what I'm doing wrong.

**Screenshots**
![image](https://user-images.githubusercontent.com/22324730/146657169-f90153c3-a617-4768-87e0-db7dd97be9f5.png)
![image](https://user-images.githubusercontent.com/22324730/146657236-db92591c-3e98-4ae6-bdda-dd4ae2c7101d.png)
![image](https://user-images.githubusercontent.com/22324730/146657246-d3a588fb-a25b-4500-a0fa-378febd912df.png)
![image](https://user-images.githubusercontent.com/22324730/146657186-7ba7e865-5639-4b87-85f5-eec4e6d89205.png)

**Comment by Lucasamiel0406** [comment]
Bruh

**Comment by Sneethan** [comment]
you are using 2.0 mods on 1.6 most likely, double check you got mods from the "old_version_1.6" branch.

**Comment by darkspyro92** [comment]
I'm not sure I'm using 1.6. On Steam I don't have any betas selected, and one of the betas is the old 1.6 branch. I'm not sure which version of DBM I'm running. The discord.js says 12.2, and I'm not running the 2.0 beta. Or do you mean that the most recent mods are meant to run on the beta and not the older version?
![image](https://user-images.githubusercontent.com/22324730/146713400-5f411fcd-4e5a-43bb-a70c-970aaa8d93a5.png)

**Comment by Sneethan** [comment]
Yeah the mods in the master branch of the git are meant for beta, change your branch on GitHub to old_version_1.6 and try

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows


________________________________

**Comment by darkspyro92** [comment]
Okay. That seems to have worked. I didn't realize that was the case. I didn't think I was on 2.0 because I thought that was the beta version that I didn't opt in for. Thank you for informing on that one.

**Comment by Sneethan** [comment]
All good.
