### ISSUE TITLE
mod_info_MOD.js | loop_queue_MOD.js causing issues with music.

### ISSUE THREAD

**Issue by WolfoTheWolf** [dbm-network/mods#824]
**Describe the bug**
both of these actions keep the play_youtube.js from working properly, the bot will just act like you never input a link.

**To Reproduce**
1. Add mod_info_MOD.js | loop_queue_MOD.js to your actions folder
2. play a song

**Expected behavior**
The bot should play a song

**Comment by almeidx** [comment]
Do not use these actions as they haven't been updated to work with the latest version of DBM, and they will be replaced by default actions at a later date.
