### ISSUE TITLE
check_variable.js when updated with the DBM Update Default Actions

### ISSUE THREAD

**Issue by WolfoTheWolf** [dbm-network/mods#825]
**Describe the bug**
When you update it replaces the default check variable, when you run a / command in your server it will fail to send a message.

**To Reproduce**
1. Remove all other mods and add the check_variable.js and let it replace it.
2. make a / command with a command.
4. it will fail to reply.
**Expected behavior**
The bot will reply normally 

((-187 Removals
+283 Additions )) on code when comparing.

**Screenshots**
![image](https://user-images.githubusercontent.com/56661068/147313979-72025c6b-a855-423b-b7ed-e909c41181f8.png)

**Comment by DetroitWhiskey136** [comment]
this action will be removed from the mod list in the next update.
