### ISSUE TITLE
Serious Variable Check Bug

### ISSUE THREAD

**Issue by Komodroid** [dbm-network/mods#832]
**Describe the bug**
The default "Check if variable" action is seriously glitched. Not sure if it's related to the 0 (zero) number or honestly what:
It fails to check if a number is less than 1

**To Reproduce**
- Set var to 0
- Check if var is less than 1: if true go to anchor "A", else continue actions
- Check if var is greater than 1: if true go to anchor "B", else go to anchor "C"
- Each anchor is properly separated by "End action sequence"
- Run the command

**Expected behavior**
- Goes to anchor "A", gets filtered by the very first var check

**Actual behavior**
- Goes to anchor "C", totally illogical 

**Raw Data**
`{
  "name": "wtf",
  "permissions": "NONE",
  "permissions2": "NONE",
  "restriction": "1",
  "_id": "LEpzV",
  "actions": [
    {
      "storage": "1",
      "varName": "_e",
      "changeType": "0",
      "value": "2",
      "name": "Control Variable"
    },
    {
      "storage": "1",
      "varName": "_e",
      "comparison": "3",
      "value": "1",
      "branch": {
        "iftrue": "4",
        "iffalse": "0",
        "iftrueVal": "No"
      },
      "name": "Check Variable"
    },
    {
      "storage": "1",
      "varName": "_e",
      "comparison": "4",
      "value": "1",
      "branch": {
        "iftrue": "4",
        "iffalse": "4",
        "iftrueVal": "Too",
        "iffalseVal": "Ok"
      },
      "name": "Check Variable"
    },
    {
      "anchorName": "Ok",
      "name": "Action Anchor"
    },
    {
      "channel": "0",
      "varName": "",
      "message": "ok ${tempVars(\"_e\")}",
      "buttons": [],
      "selectMenus": [],
      "attachments": [],
      "embeds": [],
      "reply": false,
      "ephemeral": false,
      "tts": false,
      "overwrite": false,
      "dontSend": false,
      "editMessage": "0",
      "editMessageVarName": "",
      "storage": "0",
      "varName2": "",
      "name": "Send Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "anchorName": "No",
      "name": "Action Anchor"
    },
    {
      "channel": "0",
      "varName": "",
      "message": "No ${tempVars(\"_e\")}",
      "buttons": [],
      "selectMenus": [],
      "attachments": [],
      "embeds": [],
      "reply": false,
      "ephemeral": false,
      "tts": false,
      "overwrite": false,
      "dontSend": false,
      "editMessage": "0",
      "editMessageVarName": "",
      "storage": "0",
      "varName2": "",
      "name": "Send Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "anchorName": "Too",
      "name": "Action Anchor"
    },
    {
      "channel": "0",
      "varName": "",
      "message": "Too ${tempVars(\"_e\")}",
      "buttons": [],
      "selectMenus": [],
      "attachments": [],
      "embeds": [],
      "reply": false,
      "ephemeral": false,
      "tts": false,
      "overwrite": false,
      "dontSend": false,
      "editMessage": "0",
      "editMessageVarName": "",
      "storage": "0",
      "varName2": "",
      "name": "Send Message"
    }
  ],
  "comType": "0"
}`

**Screenshots**
![Discord_Bot_Maker_O454MlMbre](https://user-images.githubusercontent.com/79285823/147810043-0150ee14-4493-4a34-81ea-63eb5556cb1f.png)

- Setting var to 1: (OK)
![Discord_ahoyMcmt8I](https://user-images.githubusercontent.com/79285823/147810088-85797932-8bec-464b-afbe-ea6f914ceffb.png)

- Setting var to 2: (OK)
![Discord_bPgFAkCPfn](https://user-images.githubusercontent.com/79285823/147810103-ee9ba220-f4a2-4872-9e45-5f37d6916fe7.png)

- Setting var to 0: (WTF?)
![Discord_Bzv3Sug78i](https://user-images.githubusercontent.com/79285823/147810127-81381892-05b3-496d-a7ef-a5e02d856f6f.png)

**Comment by ParallaxOnline** [comment]
0 as a number is equal to undefined, try wrapping 0 with "" or '' to tell node it needs to treat 0 as a char.

**Comment by DetroitWhiskey136** [comment]
If memory serves this is no longer a mod.
