### ISSUE TITLE
Music bot won't play music when other actions are installed!

### ISSUE THREAD

**Issue by supertrio17** [dbm-network/mods#841]
**Describe the bug**
Hey, so I have problems with my music bot. It doesn't play given song when other actions are installed. When I extract actions from zip file into the bot directory, it doesn't give any errors, but it just joins the channel and doesn't do anything. But when I delete all MOD actions and leave only youtube_search_MOD.js it works as expected

**Comment by TheMonDon** [comment]
Music is currently unsupported, but I do not think the issue would be from having other actions installed.
