### ISSUE TITLE
MOD: Store File Info V2

### ISSUE THREAD

**Issue by MrAndyTV** [dbm-network/mods#844]
**Describe the bug**
Not able to store as a varaible, when you set it to "tempvariable" it won't show in the right click menu. When trying to add it manuly with the "template" tempvariable it shows in discord as ${tempVars("file_content")} and not the actual content of the file.

**To Reproduce**
1. Go to 'Store File Info'
2. Add the file directory, and file.
3. Equip "TempVariable" as the way of storing it.
4. Go to you message and try adding that variable.

**Expected behavior**
I expected it to show the content of the file instead of the actual variable I used.

**Screenshots**
[Screenshot of embed message.](https://images.andreasda223.me/Discord_pb07MkHtlr.png)

**Comment by DetroitWhiskey136** [comment]
I wasn't able to reproduce this bug.

![image](https://user-images.githubusercontent.com/45453611/153911451-b05631a7-6711-4676-8c56-c30caacf5cb1.png)
![image](https://user-images.githubusercontent.com/45453611/153911489-d2f4fa1c-6972-4ad9-9fe1-83be71c7dbc9.png)
![image](https://user-images.githubusercontent.com/45453611/153911521-ca5cf074-889a-46ec-bf97-ae2cbceb1cd1.png)

**Comment by DetroitWhiskey136** [comment]
#848 fixes the variable selection issue.
