### ISSUE TITLE
Check_if_member_MOD action error

### ISSUE THREAD

**Issue by SzymonEls** [dbm-network/mods#847]
**Describe the bug**
When I start the project with the newest version of mods it shows me following error: 

> Bot has started at Monday, Feb 14, 2022, 6:54:07 PM
> ? C:\Users\User\Desktop\MyBot\actions\check
> ? _if_member_MOD.js:142
> ?      result = member.user?.bot || member.bot;
> ?      ^
> ?
> ? SyntaxError: Unexpected token '.'
> ?     at wrapSafe (internal/modules/cjs/loader.js:1072:16)
> ?     at Module._compile (internal/modules/cjs/loader.js:1122:27)
> ?     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
> ?     at Module.load (internal/modules/cjs/loader.js:1002:32)
> ?     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
> ?     at Module.require (internal/modules/cjs/loader.js:1044:19)
> ?     at require (internal/modules/cjs/helpers.js:77:18)
> ?     at Object. (C:\Users\User\Desktop\MyBot\bot.js:362:20)
> ?     at Array.forEach ()
> ?     at Object. (C:\Users\User\Desktop\MyBot\bot.js:360:23)

**To Reproduce**
1. Install mods
2. Go to _Project>Run project_

**Expected behavior**
Running project without errors.

**Screenshots**

**Comment by DetroitWhiskey136** [comment]
use the v1.6 mods when using the stable version of discord bot maker

**Comment by SzymonEls** [comment]
Ok, thank you. It works.
