### ISSUE TITLE
check_if_message_MOD.js (check if the message is deleted)

### ISSUE THREAD

**Issue by master3395** [dbm-network/mods#852]
Getting warnings for V13 usage where it seems that (check if the message is deleted) this behavior is deleted/removed.

https://github.com/discordjs/discord.js/issues/7091

**Comment by Coder-Tavi** [comment]
It's not deleted, just deprecated. It serves as a warning to the users that in the next major version (I assume `d.js v14`), the property will be removed.

**Comment by Thaliruth1** [comment]
It has already been removed!
It works only under Discord.JS 13.8.1 now

**Comment by TheMonDon** [comment]
Going to close this as it is not relevant, the option is available in Discord.JS v13 and is removed in v14, will be removed when DBM gets updated.
