### ISSUE TITLE
parse_from_stored_json_MOD.js NOT WORKING

### ISSUE THREAD

**Issue by imTrojxn** [dbm-network/mods#853]
**Describe the bug**
When you send Json to a WebAPI it works perfectly fine and when you scroll down it says to "use **Parse From Stored Json** to parse the response into a variable!" and when doing so it doesn't seem to work the way it's supposed to or at all actually. Setting the Json path to nothing just returns as **Undefined** when trying to send it as a message and when putting something there and sending it as a message it sends **{"error":"error","statusCode":0,"success":false}** but in the console it sends **WebAPI Parser: Error Invalid JSON, is the Path set correctly? [$.key_status]**

This is the response I get in the console from the **Send Json To WebAPI** action. All I want is to get the $.key_status path response which is **Assigned** as a variable so I can check it to give the Command User a role. Just incase you're wondering, yes I have redownloaded the mods plenty of times and used both the beta and normal version of DBM and still the same exact results from both. I'm not sure if there are separate mods for the beta because they aren't listed anywhere that I could find.

**To Reproduce**
1. Send Json To WebAPI
2. Save As TempVar
3. Use **Parse From Stored Json** action
4. Save As TempVar
5. Enable Debugging for both to get console errors.
6. Use **Send Message** action to see "errors" what happens when sending message using

**Expected behavior**
WebAPI Parser: Error Invalid JSON, is the Path set correctly? [path here]

**Screenshots**
![image_2022-03-01_180147](https://user-images.githubusercontent.com/97578119/156280423-f0452678-acea-4e4c-8c10-b590f83bd3d8.png)
![image](https://user-images.githubusercontent.com/97578119/156280955-34f0d071-157e-4716-bad5-9d71b7cb5bff.png)

![image](https://user-images.githubusercontent.com/97578119/156280829-f97960ba-9b22-4264-911f-30b089501ca0.png)

**Comment by Zerlingg** [comment]
I can confirm this is a problem.
I suggest you use the previous version of the action in the meantime, it works as supposed.

**Comment by TheMonDon** [comment]
This should be fixed in the latest commit.
