### ISSUE TITLE
Did DBM stop supporting steam version? Can not get DBM to work with mods.

### ISSUE THREAD

**Issue by NebulaBC** [dbm-network/mods#858]
**Describe the bug**
I have tried numerous times to create a bot, and as of currently I get the error `Error with the command "Find Channel", Action #1:                                                                       TypeError: server.channels.filter is not a function` and `TypeError: Mods.setupMusic is not a function` these are only a couple of numerous errors I have gotten though, and I can not get DBM to work with mods at all. I have tried older versions of DBM mods, and even created a windows vm (I was trying to use wine-proton at first)

**To Reproduce**
Just create a project normally and put in DBM mod actions (and then create a command, and things will fail in it)

**Comment by DetroitWhiskey136** [comment]
you're probably using the wrong version of the mods for you're DBM version,
as a general rule of thumb the master branch only supports the latest beta all other branches give the version they support

**Comment by NebulaBC** [comment]
Thanks, I will give it a go in a bit. I’m just using the latest version off of steam, but have not had issues just using the master branch in the past. I appreciate being pretty know 👍

**Comment by master3395** [comment]
> Thanks, I will give it a go in a bit. I’m just using the latest version off of steam, but have not had issues just using the master branch in the past. I appreciate being let know 👍 I ended up just putting in _only_ the mods I needed, and that seems to work fine, but now I know for the future.

The latest version on steam is 1.6 and Beta 2.x
The Master branch on GitHub is updated for 2.x

So if you want to use mods for 1.6
You need to grab it from here:
[https://github.com/dbm-network/mods/tree/old_version_v1.6](https://github.com/dbm-network/mods/tree/old_version_v1.6)
