### ISSUE TITLE
YouTube Playlist MOD action is not working.

### ISSUE THREAD

**Issue by erturkgg** [dbm-network/mods#866]
**Discord Bot Maker version (master branch only supports the beta 2.0.x)**
- [ ] <1.6.X
- [ ] 1.6.X
- [ ] 2.0.X
- [x] >2.0.X

**Describe the bug**
Play YouTube Playlist MOD is broken since past months, its not playing any kind of playlist & mix.

**To Reproduce**
1. Add Play YouTube Playlist to your Command
2. Try yourself

**Screenshots**
No screenshots.

**Error messages**
No error message on CMD, but also no action on bot.

**Comment by DetroitWhiskey136** [comment]
music currently isn't supported in v2+ we are unsure if we plan on adding support. its a really big hassle.

**Comment by TheMonDon** [comment]
YouTube is unsupported & broken, sorry.
