### ISSUE TITLE
error on start bot

### ISSUE THREAD

**Issue by joaofelipe34** [dbm-network/mods#868]
Starting bot at version: "1.6.10"
 ? C:\Users\JoaoPC\Desktop\Drip 
 ? Bot\actions\await_reaction_call_action_MOD.js:241
 ?         const author = message?.author ?? interaction?.user;
 ?                                ^
 ? 
 ? SyntaxError: Unexpected token '.'
 ?     at wrapS
 ? afe (internal/modules/cjs/loader.js:1072:16)
 ?     at Module._co
 ? mpile (internal/modules/cjs/loader.js:11
 ? 22:27)
 ?     at Object.Module._extension
 ? s..js (internal/modules/cjs/loader.js:
 ? 1178:10)
 ?     at Module.load (internal/m
 ? odules/cjs/loader.js:1002:32)
 ?     at 
 ? Function.Module._load (internal/modul
 ? es/cjs/loader.js:901:14)
 ?     at Modul
 ? e.require (internal/modules/cjs/lo
 ? ader.js:1044:19)
 ?     at require (interna
 ? l/modules/cjs/helpers.js:77:18)
 ?     a
 ? t Object.<anonymous> (C:\Users\Joao
 ? PC\Desktop\Drip Bot\bot.js:362:20)
 ? 
 ?     at Array.forEach (<anonymous>)
 ?  
 ?    at Object.<anonymous> (C:\Users\Joa
 ? oPC\Desktop\Drip Bot\bot.js:360:23
 ? )
 ?

**Comment by Lucasamiel0406** [comment]
Not something really worth to be here and already recognized on DBM Mods, follow [this guide](https://discord.com/channels/374961173524643843/374961417016573962/961453903201828874) to fix your issue.
