### ISSUE TITLE
Send embed doesnt work with store message info

### ISSUE THREAD

**Issue by JayJayItyle** [dbm-network/mods#869]
**Discord Bot Maker version (master branch only supports the beta 2.0.x)**
- The newest steam one (idk how to check)

**Describe the bug**

**To Reproduce**
1. Make an event (every mesage sent)
2. Store message info (message channel)
3. create embed
4. send embed to the channel
5. nothing happens

(tested - normal messages work, no console errors)
**Expected behavior**
An embed would be sent

**Screenshots**

**Error messages**
nope

**Comment by DetroitWhiskey136** [comment]
embed messages are normal messages with an embed object attached to the embeds property in the message object

**Comment by JayJayItyle** [comment]
> 

So? That doesn't solve my problem...

**Comment by JayJayItyle** [comment]
> embed messages are normal messages with an embed object attached to the embeds property in the message object

It works when i set it to default

**Comment by DetroitWhiskey136** [comment]
If you need support use the support channels in discord.

**Comment by JayJayItyle** [comment]
> If you need support use the support channels in discord.

can you give me the link to it bc its expired on gb pages

**Comment by JayJayItyle** [comment]
Thanks
