### ISSUE TITLE
Invite used MOD event does not trigger

### ISSUE THREAD

**Issue by NicolaisZR** [dbm-network/mods#870]
**Discord Bot Maker version (master branch only supports the beta 2.0.x)**
- [ ] <1.6.X
- [ ] 1.6.X
- [ ] 2.0.X
- [x] >2.0.X

**Describe the bug**
The event doesn't trigger anything, it just doesn't work.

**To Reproduce**
1. Create a new event with it
2. Try yourself

**Expected behavior**
That when being used an invitation should trigger the event.

**Screenshots**
No screenshots.

**Error messages**
No error messages.

**Comment by TheMonDon** [comment]
@almeidx Can you look into this one, I'm not sure how to solve it.
