### ISSUE TITLE
BUG SEND JSON WEB API

### ISSUE THREAD

**Issue by dgcardoso** [dbm-network/mods#871]
**Discord Bot Maker version (master branch only supports the beta 2.0.x)**
- [ ] <1.6.X
- [ ] 1.6.X
- [ ] 2.0.X
- [x ] >2.0.X

**Describe the bug**

**To Reproduce**

**Expected behavior**
send POST

**Screenshots**
![image](https://user-images.githubusercontent.com/100394396/163925882-3c3e9d1c-cf9e-4c4e-98a6-2a9ccab4418a.png)

**Error messages**
If there was an error message please put it here. (plain text)

**Comment by TheMonDon** [comment]
Please fill out the entire bug report properly. There's no way for us to test this.

**Comment by dgcardoso** [comment]
Discord Bot Maker version (master branch only supports the beta 2.0.x)

 <1.6.X
 1.6.X
 2.0.X
[x ] >2.0.X
Describe the bug
the api responds with Example response - 204:
// Successful
 so how i can fix it that the bot dont crash when a invalid json responds

To Reproduce
Steps to reproduce the behavior:

use 'action send json web api'
send POST

![image](https://user-images.githubusercontent.com/100394396/164010481-24ea518a-7e29-42dd-8da2-f9091fdb5e8e.png)

**Comment by OneAndonlyFinbar** [comment]
That is not a mod bug, the api is sending something not json formatted, consider checking the endpoint using reqbin.
