### ISSUE TITLE
Set Role Voice Channel Permissions needs a rework

### ISSUE THREAD

**Issue by Sneethan** [dbm-network/mods#873]
**Discord Bot Maker version (master branch only supports the beta 2.0.x)**
- [x] 2.1.1

**Describe the bug**
Many parts of Set Role Voice Channel Permissions are not working as intended. These include:
When using First server role on a temp var for the vc, it ends the interaction sequence, thus breaking slash commands.
and when trying to set the permissions based on the command user's VC it sets it for the text chat instead of the voice chat.

**To Reproduce**
1. Make a new slash command
2. Add a set role voice channel perms, or add a store member info before if you want to test the first bug as command user vc doesnt work. Then set it to first server role and deny connect permissions.
3. Run the command.
4. See errors

**Expected behavior**
The permissions for the specified role will be adjusted without the interaction sequence ending, allowing me to send a confirmation message.

**Screenshots**
![image](https://user-images.githubusercontent.com/53156475/165027517-f917b08d-b810-468d-9e9f-aea13c4e0808.png)

**Error messages**
If there was an error message please put it here. (plain text)
Error with the Command "voice lock" - Action #9 (Send Message):
DiscordAPIError: Interaction has already been acknowledged.

**Comment by Morugar** [comment]
It's 100% of truth. Don't work tho. Nothing happend when try to change permissions

**Comment by DetroitWhiskey136** [comment]
Will be updating this later this week hopefully.
