### ISSUE TITLE
Variables Don't Get Resolved in Modal Titles

### ISSUE THREAD

**Issue by realCmdData** [dbm-network/mods#875]
**Discord Bot Maker version (master branch only supports the beta 2.0.x)**
- [ ] <1.6.X
- [ ] 1.6.X
- [x] 2.0.X
- [x ] >2.0.X

**Describe the bug**
The field "Modal Title" doesn't appear to support variables in the Show Modal action 

**To Reproduce**
1. Create a command that saves something to a variable (In my case it was saving something from a previous modal) 
2. Add a variable using the right click -> insert temp variable menu
3. Observe how the variable does not resolve: https://i.imgur.com/3ZhPmdZ.png

**Expected behavior**
The variable should resolve into what it was storing and not into plain text

**Screenshots**
https://i.imgur.com/3ZhPmdZ.png

**Comment by DetroitWhiskey136** [comment]
modals aren't part of the mod pack
