### ISSUE TITLE
set_voice_channel_permissions_MOD.js don't work

### ISSUE THREAD

**Issue by Morugar** [dbm-network/mods#877]
**Discord Bot Maker version (master branch only supports the beta 2.0.x)**
- [] <1.6.X
- [] 1.6.X
- [] 2.0.X
- [✌️] >2.0.X

**Describe the bug**
Set Voice Channel Permissions do nothing. Is just don't work

**To Reproduce**
1. Create a text command int DBM
2. Try to change some permissions in any voice channels
3. Get ducked

**Expected behavior**
It's should change permissions in voice channels

**Screenshots**
Idk what to screen. There's no error. The function just don't work

**Error messages**
-

**Comment by DetroitWhiskey136** [comment]
Will be updating this later this week hopefully.
