### ISSUE TITLE
"Store channel permissions" is broken

### ISSUE THREAD

**Issue by Giingu** [dbm-network/mods#879]
**Discord Bot Maker version (master branch only supports the beta 2.0.x)**
- [x] >2.0.X

**Describe the bug**
Store channel permissions is broken, always shows "mentioned role - undefined - undefined"

**To Reproduce**
1. Add the action
2. Switch target type to member
3. Do anything
4. Save it
5. You will see it is not saving properly and instead shows "mentioned role - undefined - undefined"

**Expected behavior**
It should save the settings properly instead of always saying "mentioned role - undefined - undefined"

**Screenshots**
![image](https://user-images.githubusercontent.com/38077912/173880642-0c82e085-4e65-4554-916d-0b9d975d7cdf.png)
![image](https://user-images.githubusercontent.com/38077912/173880692-1e163066-0233-4b0e-91ff-c28b83076aea.png)

**Comment by DetroitWhiskey136** [comment]
thats just a subtitle error, we'll get to it eventually :)

**Comment by Giingu** [comment]
Im not sure if it is related but here is an error i get
![Discord_Bot_Maker_cNRlffjDwl](https://user-images.githubusercontent.com/38077912/173886530-e0bd7bb6-7b6c-4120-bd4c-92b227148fd0.png)
