### ISSUE TITLE
Set Time Restriction not saving cooldown on restart

### ISSUE THREAD

**Issue by CashyGames** [dbm-network/mods#883]
**Discord Bot Maker version (master branch only supports the beta 2.0.x)**
- [ ] <1.6.X
- [ ] 1.6.X
- [X] 2.0.X
- [ ] >2.0.X

**Describe the bug**
Set Time Restriction doesnt save the cooldown when I restart my bot even though Reset After Restart is set to False.

**To Reproduce**
1. Make a command 
2. Use Set Time Restriction and put Reset After Restart to False
3. Activate the cooldown
4. Restart bot 

**Expected behavior**
The cooldown is supposed to be active after the bots restart

**Comment by TheMonDon** [comment]
This has been resolved.
