### ISSUE TITLE
Store Command Info does not work with slash commands

### ISSUE THREAD

**Issue by Giingu** [dbm-network/mods#893]
- [x] >2.0.X

**Describe the bug**
Store Command Info does not work when used with Slash Commands

**To Reproduce**
1. Add the action on a slash command
2. Choose search command by "None (Same Command)"
3. Store it on a variable
4. Try sending it on a message or whatever

**Expected behavior**
The command name is stored and it's sent on the message

**Error messages**
C:\Users\Giingu\Desktop\Folders\Discord Bot\My Bots\Nezuko-Checker\actions\store_command_info_MOD.js:120
            `$..[?(@.name=="${cache.msg.content
                                        ^

TypeError: Cannot read properties of null (reading 'content')

**Comment by almeidx** [comment]
Fixed in #909
