### ISSUE TITLE
Check if Member is timed out

### ISSUE THREAD

**Issue by NukaSpider** [dbm-network/mods#898]
**Is your feature request related to a problem? Please describe.**

**Describe the ideal solution**
In the existing Check if Member mod, add Check if Member is timed out

**Describe alternatives you've considered**

**Additional context**

**Comment by OneAndonlyFinbar** [comment]
You're supposed to fill in the placeholders.. 😉

**Comment by OneAndonlyFinbar** [comment]
Added in #899, waiting for a merge.
