### ISSUE TITLE
Check

### ISSUE THREAD

**Issue by Scriptedisles** [dbm-network/mods#905]
- [ ] 2.0.X

**Describe the bug**
Check if member source member option shows variables instead of slash parameters when slash parameters are chosen.

**To Reproduce**
1.Add the action on a slash command
2. Change the source Member option

**Screenshots**

![image](https://user-images.githubusercontent.com/62614570/188757399-cc35db32-7f1e-4694-92d9-7be683b7d830.png)

**Comment by Scriptedisles** [comment]
No reply still?

**Comment by TheMonDon** [comment]
@almeidx Suggestions on how to fix this?

**Comment by almeidx** [comment]
@TheMonDon The action should use the new `member-input` HTML element instead of whats's currently used. You can take a look at the default actions for inspiration
