### ISSUE TITLE
Play Youtube Video not working!

### ISSUE THREAD

**Issue by supertrio17** [dbm-network/mods#911]
Playing youtube video, and music bots overall do not work!

**Comment by Gotowka** [comment]
You can use my mods to play music, https://github.com/Gotowka/mydbm/blob/main/actions/play_all.js

**Comment by Treefchan** [comment]
Try installing the youtube-dl-exec module version 2.0.14 Here is the instruction:
https://youtu.be/LdB44HBbekg
