### ISSUE TITLE
Store User Info: Avatar URL not a function.

### ISSUE THREAD

**Issue by fsb-py** [dbm-network/mods#920]
**Discord Bot Maker version (master branch only supports the beta 2.0.x)**
- [ ] <1.6.X
- [ ] 1.6.X
- [ ] 2.0.X
- [X] >2.0.X

**Describe the bug**
I'm requesting the user avatar, i'm getting this error.

**To Reproduce**
1. Go to 'Temp Var'
2. Click on 'User Avatar Url and store it'
3. Send the avatar via embedded message, right click and put the temp var for avatar url and send the command.

**Expected behavior**
Send the user's avatar

**Screenshots**
![User Store Avatar image](https://user-images.githubusercontent.com/121447417/211169816-3ad59f12-1ee6-4a46-b490-fa48cf93baa6.png)
![Embed image](https://user-images.githubusercontent.com/121447417/211169827-e2d839de-9a81-44cf-984e-c0abc9a9c020.png)
![Error image](https://user-images.githubusercontent.com/121447417/211169832-5f9984e7-63ff-402c-b7ce-a3ae2d5eba86.png)

**Error messages**

? C:\Users\onlya\Desktop\valid\actions\store_user_info_MOD.js:155
?      result = user.displayAvatarURL({
?      ^
?
? TypeError: user.displayAvatarURL is not a function
?     at Object.action [as Store User Info] (C:\Users\onlya\Desktop\valid\actions\store_user_info_MOD.js:155:23)
?     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by fsb-py** [comment]
I'm getting the user via there id and everything else is working except the avatar.

**Comment by TheMonDon** [comment]
This looks like the user was not found

**Comment by TheMonDon** [comment]
Closing as this is user error, action works fine for me.
