### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by Yur-ie** [dbm-network/mods#924]
**Describe the bug**
Can't create tables using 'proper' SQL

**To Reproduce**
1. Run an SQL query with the following as listed below
2. Check logs

**NOTES**
This does **NOT** apply with pushing/pulling data, only with creating tables. This might be a format/syntax issue but it works perfectly outside of DBM

```sql
CREATE TABLE IF NOT EXISTS `config` (
  `flag` text NOT NULL,
  `rule` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

CREATE TABLE IF NOT EXISTS `logs` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Hash` text DEFAULT NULL,
  `userid` bigint(20) unsigned DEFAULT NULL,
  `channel` bigint(20) unsigned DEFAULT NULL,
  `command` text DEFAULT NULL,
  `status` text DEFAULT NULL,
  `Var1` text DEFAULT NULL,
  `Var2` text DEFAULT NULL,
  `Var3` text DEFAULT NULL,
  `Var4` text DEFAULT NULL,
  `Var5` text DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

CREATE TABLE IF NOT EXISTS `messages` (
  `msgID` bigint(99) DEFAULT NULL,
  `serverID` bigint(99) DEFAULT NULL,
  `channelID` bigint(99) DEFAULT NULL,
  `author` bigint(99) DEFAULT NULL,
  `msg` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

CREATE TABLE IF NOT EXISTS `test` (
  `abc` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

CREATE TABLE IF NOT EXISTS `vcban` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `banned` bigint(99) DEFAULT NULL,
  `reason` text DEFAULT NULL,
  `banner` int(11) DEFAULT NULL,
  `time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci; 
```

**Expected behavior**
It should create a table with the proper information provided

**Screenshots**
![image](https://user-images.githubusercontent.com/91012163/214402800-71216e1a-d235-46c2-a7ac-0ca562e05bd7.png)

**Error messages**
```? Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CREATE TABLE IF NOT EXISTS `logs` (
? `ID` int(11) NOT NULL AUTO_INCREMENT,
? ...' at line 6
?     at Packet.asError (C:\Program Files (x86)\Discord Bots\T-Rex Bot\node_modules\mysql2\lib\packets\packet.js:728:17)
?     at Query.execute (C:\Program Files (x86)\Discord Bots\T-Rex Bot\node_modules\mysql2\lib\commands\command.js:29:26)
?     at Connection.handlePacket (C:\Program Files (x86)\Discord Bots\T-Rex Bot\node_modules\mysql2\lib\connection.js:487:32)
?     at PacketParser.onPacket (C:\Program Files (x86)\Discord Bots\T-Rex Bot\node_modules\mysql2\lib\connection.js:94:12)
?     at PacketParser.executeStart (C:\Program Files (x86)\Discord Bots\T-Rex Bot\node_modules\mysql2\lib\packet_parser.js:75:16)
?     at Socket. (C:\Program Files (x86)\Discord Bots\T-Rex Bot\node_modules\mysql2\lib\connection.js:101:25)
?     at Socket.emit (node:events:520:28)
?     at addChunk (node:internal/streams/readable:324:12)
?     at readableAddChunk (node:internal/streams/readable:297:9)
?     at Socket.Readable.push (node:internal/streams/readable:234:10) {
? code: 'ER_PARSE_ERROR',
? errno: 1064,
? sqlState: '42000',
? sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CREATE TABLE IF NOT EXISTS `logs` (\n" +
?     ' `ID` int(11) NOT NULL AUTO_INCREMENT,\n' +
?     " ...' at line 6",
? sql: 'CREATE TABLE IF NOT EXISTS `config` (\n' +
?     ' `flag` text NOT NULL,\n' +
?     ' `rule` text NOT NULL\n' +
?     ') ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;\n' +
?     '\n' +
?     'CREATE TABLE IF NOT EXISTS `logs` (\n' +
?     ' `ID` int(11) NOT NULL AUTO_INCREMENT,\n' +
?     ' `Hash` text DEFAULT NULL,\n' +
?     ' `userid` bigint(20) unsigned DEFAULT NULL,\n' +
?     ' `channel` bigint(20) unsigned DEFAULT NULL,\n' +
?     ' `command` text DEFAULT NULL,\n' +
?     ' `status` text DEFAULT NULL,\n' +
?     ' `Var1` text DEFAULT NULL,\n' +
?     ' `Var2` text DEFAULT NULL,\n' +
?     ' `Var3` text DEFAULT NULL,\n' +
?     ' `Var4` text DEFAULT NULL,\n' +
?     ' `Var5` text DEFAULT NULL,\n' +
?     ' PRIMARY KEY (`ID`)\n' +
?     ') ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;\n' +
?     '\n' +
?     'CREATE TABLE IF NOT EXISTS `messages` (\n' +
?     ' `msgID` bigint(99) DEFAULT NULL,\n' +
?     ' `serverID` bigint(99) DEFAULT NULL,\n' +
?     ' `channelID` bigint(99) DEFAULT NULL,\n' +
?     ' `author` bigint(99) DEFAULT NULL,\n' +
?     ' `msg` text DEFAULT NULL\n' +
?     ') ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;\n' +
?     '\n' +
?     'CREATE TABLE IF NOT EXISTS `test` (\n' +
?     ' `abc` text DEFAULT NULL\n' +
?     ') ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;\n' +
?     '\n' +
?     'CREATE TABLE IF NOT EXISTS `vcban` (\n' +
?     ' `ID` int(11) NOT NULL AUTO_INCREMENT,\n' +
?     ' `banned` bigint(99) DEFAULT NULL,\n' +
?     ' `reason` text DEFAULT NULL,\n' +
?     ' `banner` int(11) DEFAULT NULL,\n' +
?     ' `time` timestamp NULL DEFAULT NULL,\n' +
?     ' PRIMARY KEY (`ID`)\n' +
?     ') ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;',
? parameters: undefined
? }```

**Comment by Yur-ie** [comment]
Updated to have the right screenshots & Information

**Comment by OneAndonlyFinbar** [comment]
This is not a mod issue.
