### ISSUE TITLE
Delete member data doesn't work unless deleting all off a member's data

### ISSUE THREAD

**Issue by MisterFyre** [dbm-network/mods#930]
**Discord Bot Maker version (master branch only supports the beta 2.0.x)**
- [ ] <1.6.X
- [ ] 1.6.X
- [ ] 2.0.X
- [x ] >2.0.X

**Describe the bug**

Delete member data doesn't delete specific member data (only works when deleting all of a member's data)

**To Reproduce**
1. Go to 'DBM'
2. Click on 'Run project'
3. Scroll down to 'any command or event that is meant to delete a specific type of member data'

**Expected behavior**

The specific member data im trying to have deleted be removed from the players.json file

**Screenshots**

**Error messages**
If there was an error message please put it here. (plain text)

**Comment by MisterFyre** [comment]
there is none, it just doesn't do it. i think i did get it to remove the number on the member data once, but it didn't remove the member id with it

**Comment by ForceBlood** [comment]
Seems to be working just fine for me, are you sure you are using the action correctly?

**Comment by OneAndonlyFinbar** [comment]
Likely caused by user error and not mod bug, non reproducible error.
