### ISSUE TITLE
Cleverbot Action Broken (cleverbot.com api)

### ISSUE THREAD

**Issue by MisterFyre** [dbm-network/mods#931]
**Discord Bot Maker version (master branch only supports the beta 2.0.x)**
- [ ] <1.6.X
- [ ] 1.6.X
- [ ] 2.0.X
- [ x] >2.0.X

**Describe the bug**

Whenever i trigger the cleverbot action (even with the cleverbot-node module installed via cmd), it crashes after some time.

**To Reproduce**
1. Go to 'DBM'
2. Click on 'Run Project, or Run Project Independently'
3. Scroll down to 'Trigger any command or event that uses the cleverbot action (cleverbot.com mode)'
4. wait a minute or two
5. See error

**Expected behavior**

The action sending a response to a temp variable, which would get sent to the message.

**Screenshots**
![image](https://user-images.githubusercontent.com/105957925/220796676-b86889d9-ee91-45ec-b75b-bf398479d142.png)

**Error messages**
If there was an error message please put it here. (plain text)

? npm WARN deprecated superagent@7.1.6: Please downgrade to v7.1.5 if you need IE/ActiveXObject support OR upgrade to v8.0.0 as we no longer support IE and published an incorrect patch version (see https://github.com/visionmedia/superagent/issues/1731)
? npm ERR! code 1
? npm ERR! path C:\Users\xxxxx\OneDrive\Desktop\Wild Computer Bot\node_modules\youtube-dl-exec
? npm ERR! command failed
? npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npx bin-version-check-cli python3 "> =3.7" || npx bin-version-check-cli python "> =3.7"
? npm ERR! Error: Couldn't find version of `python3`
? npm ERR!     at binaryVersion (file:///C:/Users/xxxxx/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version/index.js:55:8)
? npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
? npm ERR!     at async binaryVersionCheck (file:///C:/Users/xxxxx/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version-check/index.js:14:18)
? npm ERR! Error: Couldn't find version of `python`
? npm ERR!     at binaryVersion (file:///C:/Users/xxxxx/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version/index.js:55:8)
? npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
? npm ERR!     at async binaryVersionCheck (file:///C:/Users/xxxxx/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version-check/index.js:14:18)
?
? npm ERR! A complete log of this run can be found in:
? npm ERR!     C:\Users\xxxxx\AppData\Local\npm-cache\_logs\2023-02-23T00_40_46_199Z-debug-0.log
?
? node:child_process:828
?     err = new Error(msg);
?      ^
?
? Error: Command failed: npm i cleverbot-node
? npm WARN deprecated superagent@7.1.6: Please downgrade to v7.1.5 if you need IE/ActiveXObject support OR upgrade to v8.0.0 as we no longer support IE and published an incorrect patch version (see https://github.com/visionmedia/superagent/issues/1731)
? npm ERR! code 1
? npm ERR! path C:\Users\xxxxx\OneDrive\Desktop\Wild Computer Bot\node_modules\youtube-dl-exec
? npm ERR! command failed
? npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npx bin-version-check-cli python3 "> =3.7" || npx bin-version-check-cli python "> =3.7"
? npm ERR! Error: Couldn't find version of `python3`
? npm ERR!     at binaryVersion (file:///C:/Users/xxxxx/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version/index.js:55:8)
? npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
? npm ERR!     at async binaryVersionCheck (file:///C:/Users/xxxxx/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version-check/index.js:14:18)
? npm ERR! Error: Couldn't find version of `python`
? npm ERR!     at binaryVersion (file:///C:/Users/xxxxx/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version/index.js:55:8)
? npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
? npm ERR!     at async binaryVersionCheck (file:///C:/Users/xxxxx/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version-check/index.js:14:18)
?
? npm ERR! A complete log of this run can be found in:
? npm ERR!     C:\Users\xxxxx\AppData\Local\npm-cache\_logs\2023-02-23T00_40_46_199Z-debug-0.log
?
?     at checkExecSyncError (node:child_process:828:11)
?     at Object.execSync (node:child_process:902:15)
?     at C:\Users\xxxxx\OneDrive\Desktop\Wild Computer Bot\actions\aaa_dbmmods_dependencies_MOD.js:6:32
?     at new Promise ()
?     at Object.installModule (C:\Users\xxxxx\OneDrive\Desktop\Wild Computer Bot\actions\aaa_dbmmods_dependencies_MOD.js:5:12)
?     at Object.require (C:\Users\xxxxx\OneDrive\Desktop\Wild Computer Bot\actions\aaa_dbmmods_dependencies_MOD.js:19:12)
?     at Object.action [as Cleverbot] (C:\Users\xxxxx\OneDrive\Desktop\Wild Computer Bot\actions\cleverbot_MOD.js:132:35)
?     at Object.Actions.callNextAction (C:\Users\xxxxx\OneDrive\Desktop\Wild Computer Bot\bot.js:1509:21)
?     at Object.action [as Store Message Info] (C:\Users\xxxxx\OneDrive\Desktop\Wild Computer Bot\actions\store_message_info.js:291:10)
?     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
? status: 1,
? signal: null,
? output: [
?     null,
?     Buffer(0) [Uint8Array] [],
?     Buffer(1538) [Uint8Array] [
?      110, 112, 109, 32, 87, 65, 82, 78, 32, 100, 101, 112,
?      114, 101, 99, 97, 116, 101, 100, 32, 115, 117, 112, 101,
?      114, 97, 103, 101, 110, 116, 64, 55, 46, 49, 46, 54,
?      58, 32, 80, 108, 101, 97, 115, 101, 32, 100, 111, 119,
?      110, 103, 114, 97, 100, 101, 32, 116, 111, 32, 118, 55,
?      46, 49, 46, 53, 32, 105, 102, 32, 121, 111, 117, 32,
?      110, 101, 101, 100, 32, 73, 69, 47, 65, 99, 116, 105,
?      118, 101, 88, 79, 98, 106, 101, 99, 116, 32, 115, 117,
?      112, 112, 111, 114,
?      ... 1438 more items
?     ]
? ],
? pid: 32152,
? stdout: Buffer(0) [Uint8Array] [],
? stderr: Buffer(1538) [Uint8Array] [
?     110, 112, 109, 32, 87, 65, 82, 78, 32, 100, 101, 112,
?     114, 101, 99, 97, 116, 101, 100, 32, 115, 117, 112, 101,
?     114, 97, 103, 101, 110, 116, 64, 55, 46, 49, 46, 54,
?      58, 32, 80, 108, 101, 97, 115, 101, 32, 100, 111, 119,
?     110, 103, 114, 97, 100, 101, 32, 116, 111, 32, 118, 55,
?      46, 49, 46, 53, 32, 105, 102, 32, 121, 111, 117, 32,
?     110, 101, 101, 100, 32, 73, 69, 47, 65, 99, 116, 105,
?     118, 101, 88, 79, 98, 106, 101, 99, 116, 32, 115, 117,
?     112, 112, 111, 114,
?     ... 1438 more items
? ]
? }
?
? Node.js v17.4.0
?

(despite it saying cleverbot-node not being findable, it was installed)

**Comment by TheMonDon** [comment]
Not a mod issue, downgrade superagent like it says.
