### ISSUE TITLE
Store Invite Info doesn't work anymore

### ISSUE THREAD

**Issue by deag69** [dbm-network/mods#932]
**Discord Bot Maker version (master branch only supports the beta 2.0.x)**
- [ ] <1.6.X
- [ ] 1.6.X
- [ ] 2.0.X
- [X] >2.0.X

**Describe the bug**
When using „Store Invite Info“, you always get „undefined“ as a result. Seems like it's outdated.

**To Reproduce**
Just try to use the action with an existing invite and any type of info.

**Expected behavior**
Getting the requested info :)

**Error messages**
None

**Comment by OneAndonlyFinbar** [comment]
Can you share rawdata?

**Comment by deag69** [comment]
> Can you share rawdata?

Sure, it's just a two action test command. I changed the Invite code because I don't want to publish it:

`{
  "name": "invitetest",
  "permissions": "NONE",
  "permissions2": "NONE",
  "restriction": "1",
  "_id": "RPhxW",
  "actions": [
    {
      "invite": "NY24yGAd",
      "info": "8",
      "storage": "1",
      "varName": "timesUsed",
      "name": "Store Invite Info"
    },
    {
      "channel": "0",
      "varName": "",
      "message": "${tempVars(\"timesUsed\")}",
      "buttons": [],
      "selectMenus": [],
      "attachments": [],
      "embeds": [],
      "reply": true,
      "ephemeral": false,
      "tts": false,
      "overwrite": false,
      "dontSend": false,
      "editMessage": "0",
      "editMessageVarName": "",
      "storage": "0",
      "varName2": "",
      "name": "Send Message"
    }
  ],
  "comType": "0"
}`
