### ISSUE TITLE
Addition: Send Transcript Mod

### ISSUE THREAD

**Issue by TheMonDon** [dbm-network/mods#980]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the ideal solution**
A mod that will send the file the transcript mod creates without needing to use file control

**Describe alternatives you've considered**
Not using DBM

**Additional context**
N/A

**Comment by dbmIsaac** [comment]
what are you actually asking for, I'm confused a little on the request.

**Comment by TheMonDon** [comment]
Decided not to do this
