### ISSUE TITLE
Store Embed Info is storing message and not embed object

### ISSUE THREAD

**Issue by MisterFyre** [dbm-network/mods#981]
**Discord Bot Maker version (master branch only supports the beta 2.0.x)**
- [ ] <1.6.X
- [ ] 1.6.X
- [ ] 2.0.X
- [ x] >2.0.X

**Describe the bug**

The "Embed Edit Object" (and possibly "Store Embed Info") actions aren't working.

**To Reproduce**
1. Go to 'DBM'
2. Click on 'Start Project'
3. Scroll down to 'Perform the command or event that makes use of editing embed text'

**Expected behavior**

The embed text to be edited.

**Screenshots**

**Error messages**
If there was an error message please put it here. (plain text)

? D:\TestFury\actions\edit_embed_object_MOD.js:600
?      embed.setDescription(description);
?      ^
?
? TypeError: embed.setDescription is not a function
?     at Object.action (D:\TestFury\actions\edit_embed_object_MOD.js:600:15)
?     at Object.Actions.callNextAction (D:\TestFury\bot.js:1511:21)
?     at Object.action [as Store Embed Info] (D:\TestFury\actions\store_embed_info_MOD.js:136:10)
?     at Object.Actions.callNextAction (D:\TestFury\bot.js:1511:21)
?     at Object. (D:\TestFury\actions\show_modal.js:231:16)
?     at Object.Actions.checkModalSubmitResponses (D:\TestFury\bot.js:2433:47)
?     at Object.Bot.onInteraction (D:\TestFury\bot.js:940:13)
?     at Client.emit (node:events:520:28)
?     at InteractionCreateAction.handle (D:\TestFury\node_modules\discord.js\src\client\actions\InteractionCreate.js:83:12)
?     at Object.module.exports [as INTERACTION_CREATE] (D:\TestFury\node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:4:36)
?
? Node.js v17.4.0
?

**Comment by TheMonDon** [comment]
Confirmed bug, will fix.
