### ISSUE TITLE
an action for detecting known phishing links

### ISSUE THREAD

**Issue by MisterFyre** [dbm-network/mods#994]
idk how it could play out, but i belive the action could use some sort of api, or have all the domains in some sort of local list to check for when the action is used

i just think this would be really cool if possible

**Comment by OneAndonlyFinbar** [comment]
This seems like something that could be done using multiple preexisting actions and shouldnt require a new dedicated action

**Comment by MisterFyre** [comment]
What actions can detect phishing links?

**Comment by Phyrok** [comment]
https://github.com/mitchellkrogza/Phishing.Database

Check Variable

**Comment by OneAndonlyFinbar** [comment]
Too specific to be an action.
