### ISSUE TITLE
Publish Discord

### ISSUE THREAD

**Issue by itsfranciscooli** [dbm-network/mods#998]
I would like to request a feature to either auto publish messages in a channel or publish messages in a certain variable.

**Comment by Phyrok** [comment]
Auto Publish & Certain Variables is extremely vague, please explain it more, because everything you say is already possible in it's basic form.

**Comment by itsfranciscooli** [comment]
My ideia is a mod that allows to publish messages in announcement channels. With this kind of command we can auto publish messages from bots or people and spread over multiiple servers.

**Comment by Phyrok** [comment]
You mean send message in an "announcement" channel and the bot automatically publishes it?

Or you mean a command from the bot to then message all the other servers?

**Comment by itsfranciscooli** [comment]
I mean your first option.

**Comment by itsfranciscooli** [comment]
My ideia is a mod that will allow me to make something similar to this: https://github.com/Vedinsoh/Discord-Auto-Publisher

**Comment by TheMonDon** [comment]
This is already a thing, you use this mod: 
https://github.com/dbm-network/mods/blob/master/actions/crosspost_message_MOD.js

You would have to make your own event for automation though.

**Comment by itsfranciscooli** [comment]
From my testing, i haven't been able to implement this feature with that mod.
